// Code generated by goyacc -o parser.go parser.go.y. DO NOT EDIT.

//line parser.go.y:2
package parser

import __yyfmt__ "fmt"

//line parser.go.y:2

import (
	"github.com/mattn/anko/ast"
)

//line parser.go.y:34
type yySymType struct {
	yys                 int
	compstmt            []ast.Stmt
	stmt_var_or_lets    ast.Stmt
	stmt_var            ast.Stmt
	stmt_lets           ast.Stmt
	stmt_if             ast.Stmt
	stmt_switch         ast.Stmt
	stmt_switch_cases   ast.Stmt
	stmt_switch_case    ast.Stmt
	stmt_switch_default []ast.Stmt
	stmt_select         ast.Stmt
	stmt_select_cases   ast.Stmt
	stmt_select_case    ast.Stmt
	stmt_select_default []ast.Stmt
	stmts               []ast.Stmt
	stmt                ast.Stmt
	expr                ast.Expr
	exprs               []ast.Expr
	map_expr            map[ast.Expr]ast.Expr
	expr_idents         []string
	expr_type           string
	tok                 ast.Token
	array_count         ast.ArrayCount
	expr_slice          ast.Expr
	expr_ident          ast.Expr
}

const IDENT = 57346
const NUMBER = 57347
const STRING = 57348
const ARRAY = 57349
const VARARG = 57350
const FUNC = 57351
const RETURN = 57352
const VAR = 57353
const THROW = 57354
const IF = 57355
const ELSE = 57356
const FOR = 57357
const IN = 57358
const EQEQ = 57359
const NEQ = 57360
const GE = 57361
const LE = 57362
const OROR = 57363
const ANDAND = 57364
const NEW = 57365
const TRUE = 57366
const FALSE = 57367
const NIL = 57368
const NILCOALESCE = 57369
const MODULE = 57370
const TRY = 57371
const CATCH = 57372
const FINALLY = 57373
const PLUSEQ = 57374
const MINUSEQ = 57375
const MULEQ = 57376
const DIVEQ = 57377
const ANDEQ = 57378
const OREQ = 57379
const BREAK = 57380
const CONTINUE = 57381
const PLUSPLUS = 57382
const MINUSMINUS = 57383
const POW = 57384
const SHIFTLEFT = 57385
const SHIFTRIGHT = 57386
const SWITCH = 57387
const SELECT = 57388
const CASE = 57389
const DEFAULT = 57390
const GO = 57391
const CHAN = 57392
const MAKE = 57393
const OPCHAN = 57394
const TYPE = 57395
const LEN = 57396
const DELETE = 57397
const UNARY = 57398

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"NUMBER",
	"STRING",
	"ARRAY",
	"VARARG",
	"FUNC",
	"RETURN",
	"VAR",
	"THROW",
	"IF",
	"ELSE",
	"FOR",
	"IN",
	"EQEQ",
	"NEQ",
	"GE",
	"LE",
	"OROR",
	"ANDAND",
	"NEW",
	"TRUE",
	"FALSE",
	"NIL",
	"NILCOALESCE",
	"MODULE",
	"TRY",
	"CATCH",
	"FINALLY",
	"PLUSEQ",
	"MINUSEQ",
	"MULEQ",
	"DIVEQ",
	"ANDEQ",
	"OREQ",
	"BREAK",
	"CONTINUE",
	"PLUSPLUS",
	"MINUSMINUS",
	"POW",
	"SHIFTLEFT",
	"SHIFTRIGHT",
	"SWITCH",
	"SELECT",
	"CASE",
	"DEFAULT",
	"GO",
	"CHAN",
	"MAKE",
	"OPCHAN",
	"TYPE",
	"LEN",
	"DELETE",
	"'='",
	"'?'",
	"':'",
	"','",
	"'>'",
	"'<'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"UNARY",
	"'{'",
	"'}'",
	"';'",
	"'('",
	"')'",
	"'['",
	"']'",
	"'.'",
	"'!'",
	"'^'",
	"'&'",
	"'|'",
	"'\\n'",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.go.y:865

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 2,
	56, 64,
	59, 64,
	70, 5,
	-2, 1,
	-1, 17,
	56, 64,
	-2, 59,
	-1, 22,
	59, 65,
	-2, 27,
	-1, 53,
	56, 64,
	59, 64,
	-2, 5,
	-1, 65,
	16, 60,
	59, 60,
	-2, 143,
	-1, 110,
	1, 79,
	8, 79,
	47, 79,
	48, 79,
	56, 79,
	58, 79,
	59, 79,
	68, 79,
	69, 79,
	70, 79,
	72, 79,
	74, 79,
	80, 79,
	-2, 74,
	-1, 112,
	1, 81,
	8, 81,
	47, 81,
	48, 81,
	56, 81,
	58, 81,
	59, 81,
	68, 81,
	69, 81,
	70, 81,
	72, 81,
	74, 81,
	80, 81,
	-2, 74,
	-1, 157,
	17, 0,
	18, 0,
	-2, 105,
	-1, 158,
	17, 0,
	18, 0,
	-2, 106,
	-1, 224,
	58, 5,
	-2, 64,
	-1, 233,
	74, 157,
	-2, 149,
	-1, 236,
	69, 157,
	-2, 149,
	-1, 253,
	1, 67,
	8, 67,
	47, 67,
	48, 67,
	56, 67,
	58, 67,
	59, 67,
	69, 67,
	70, 67,
	72, 67,
	74, 67,
	80, 67,
	-2, 74,
	-1, 263,
	1, 24,
	47, 24,
	48, 24,
	58, 24,
	69, 24,
	70, 24,
	80, 24,
	-2, 124,
	-1, 265,
	1, 26,
	47, 26,
	48, 26,
	58, 26,
	69, 26,
	70, 26,
	80, 26,
	-2, 126,
	-1, 289,
	69, 155,
	74, 155,
	-2, 150,
	-1, 308,
	1, 23,
	47, 23,
	48, 23,
	58, 23,
	69, 23,
	70, 23,
	80, 23,
	-2, 123,
	-1, 309,
	1, 25,
	47, 25,
	48, 25,
	58, 25,
	69, 25,
	70, 25,
	80, 25,
	-2, 125,
}

const yyPrivate = 57344

const yyLast = 3000

var yyAct = [...]int{

	57, 273, 274, 22, 28, 7, 234, 9, 221, 222,
	118, 5, 55, 191, 62, 58, 236, 8, 64, 276,
	275, 8, 68, 224, 223, 233, 103, 104, 298, 300,
	290, 107, 108, 109, 111, 113, 248, 8, 110, 112,
	192, 106, 299, 119, 51, 242, 8, 324, 184, 124,
	1, 116, 8, 297, 22, 309, 8, 308, 56, 243,
	55, 130, 242, 294, 286, 126, 296, 270, 115, 242,
	143, 144, 146, 147, 288, 149, 150, 151, 152, 153,
	154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
	164, 165, 166, 167, 168, 141, 120, 169, 170, 171,
	172, 125, 174, 175, 264, 193, 262, 179, 195, 245,
	123, 239, 134, 231, 122, 216, 178, 140, 6, 187,
	121, 138, 190, 55, 54, 137, 197, 370, 196, 183,
	369, 362, 360, 202, 359, 114, 355, 205, 287, 207,
	200, 55, 354, 351, 340, 173, 214, 335, 206, 331,
	330, 317, 292, 306, 271, 129, 260, 129, 256, 117,
	117, 185, 129, 254, 137, 189, 129, 366, 265, 209,
	263, 204, 365, 199, 343, 240, 333, 230, 132, 217,
	135, 227, 201, 323, 203, 322, 210, 211, 219, 285,
	208, 131, 105, 237, 66, 338, 129, 198, 129, 232,
	137, 252, 301, 136, 319, 253, 128, 244, 246, 129,
	314, 280, 364, 266, 276, 275, 269, 307, 88, 89,
	90, 91, 92, 93, 117, 22, 282, 218, 79, 279,
	278, 277, 281, 133, 361, 224, 223, 261, 101, 293,
	10, 55, 60, 251, 200, 295, 137, 291, 117, 258,
	247, 302, 192, 127, 229, 228, 117, 100, 63, 70,
	305, 73, 148, 59, 98, 96, 44, 4, 43, 29,
	35, 53, 2, 39, 313, 312, 52, 315, 194, 186,
	220, 20, 272, 311, 19, 16, 24, 46, 36, 37,
	38, 23, 325, 3, 0, 55, 117, 0, 326, 0,
	0, 327, 328, 0, 235, 235, 303, 0, 304, 0,
	0, 0, 0, 0, 0, 47, 48, 0, 45, 49,
	0, 316, 0, 0, 0, 0, 0, 30, 34, 0,
	0, 318, 41, 0, 0, 42, 321, 40, 283, 117,
	31, 32, 33, 0, 0, 357, 0, 0, 358, 0,
	0, 0, 289, 0, 0, 289, 0, 0, 334, 0,
	0, 0, 0, 0, 0, 336, 0, 0, 0, 0,
	339, 0, 0, 341, 342, 0, 0, 0, 0, 0,
	0, 0, 0, 349, 350, 0, 0, 0, 352, 353,
	0, 117, 0, 0, 356, 0, 0, 0, 0, 0,
	0, 0, 102, 82, 83, 85, 87, 97, 99, 0,
	0, 0, 0, 72, 0, 0, 367, 368, 88, 89,
	90, 91, 92, 93, 0, 0, 94, 95, 79, 80,
	81, 0, 0, 0, 0, 0, 0, 0, 101, 0,
	0, 0, 0, 71, 0, 347, 84, 86, 74, 75,
	76, 77, 78, 0, 0, 0, 0, 100, 346, 70,
	0, 73, 0, 0, 98, 96, 102, 82, 83, 85,
	87, 97, 99, 0, 0, 0, 0, 72, 0, 0,
	0, 0, 88, 89, 90, 91, 92, 93, 0, 0,
	94, 95, 79, 80, 81, 0, 0, 0, 0, 0,
	0, 0, 101, 0, 0, 0, 0, 71, 0, 250,
	84, 86, 74, 75, 76, 77, 78, 0, 0, 0,
	0, 100, 249, 70, 0, 73, 0, 0, 98, 96,
	102, 82, 83, 85, 87, 97, 99, 0, 0, 0,
	0, 72, 0, 0, 0, 0, 88, 89, 90, 91,
	92, 93, 0, 0, 94, 95, 79, 80, 81, 0,
	0, 0, 0, 0, 0, 0, 101, 0, 0, 0,
	0, 71, 225, 0, 84, 86, 74, 75, 76, 77,
	78, 0, 0, 0, 0, 100, 0, 70, 226, 73,
	0, 0, 98, 96, 102, 82, 83, 85, 87, 97,
	99, 0, 0, 0, 0, 72, 0, 0, 0, 0,
	88, 89, 90, 91, 92, 93, 0, 0, 94, 95,
	79, 80, 81, 0, 0, 0, 0, 0, 0, 0,
	101, 0, 0, 0, 0, 71, 212, 0, 84, 86,
	74, 75, 76, 77, 78, 0, 0, 0, 0, 100,
	0, 70, 213, 73, 0, 0, 98, 96, 102, 82,
	83, 85, 87, 97, 99, 0, 0, 0, 0, 72,
	0, 0, 0, 0, 88, 89, 90, 91, 92, 93,
	0, 0, 94, 95, 79, 80, 81, 0, 0, 0,
	0, 0, 0, 0, 101, 0, 0, 0, 69, 71,
	0, 0, 84, 86, 74, 75, 76, 77, 78, 0,
	139, 0, 0, 100, 0, 70, 0, 73, 0, 0,
	98, 96, 102, 82, 83, 85, 87, 97, 99, 0,
	0, 0, 0, 72, 0, 0, 0, 0, 88, 89,
	90, 91, 92, 93, 0, 0, 94, 95, 79, 80,
	81, 0, 0, 0, 0, 0, 0, 0, 101, 0,
	0, 0, 0, 71, 0, 0, 84, 86, 74, 75,
	76, 77, 78, 0, 0, 0, 0, 100, 363, 70,
	0, 73, 0, 0, 98, 96, 102, 82, 83, 85,
	87, 97, 99, 0, 0, 0, 0, 72, 0, 0,
	0, 0, 88, 89, 90, 91, 92, 93, 0, 0,
	94, 95, 79, 80, 81, 0, 0, 0, 0, 0,
	0, 0, 101, 0, 0, 0, 0, 71, 0, 0,
	84, 86, 74, 75, 76, 77, 78, 0, 0, 0,
	0, 100, 348, 70, 0, 73, 0, 0, 98, 96,
	102, 82, 83, 85, 87, 97, 99, 0, 0, 0,
	0, 72, 0, 0, 0, 0, 88, 89, 90, 91,
	92, 93, 0, 0, 94, 95, 79, 80, 81, 0,
	0, 0, 0, 0, 0, 0, 101, 0, 0, 0,
	0, 71, 0, 0, 84, 86, 74, 75, 76, 77,
	78, 0, 0, 0, 0, 100, 345, 70, 0, 73,
	0, 0, 98, 96, 102, 82, 83, 85, 87, 97,
	99, 0, 0, 0, 0, 72, 0, 0, 0, 0,
	88, 89, 90, 91, 92, 93, 0, 0, 94, 95,
	79, 80, 81, 0, 0, 0, 0, 0, 0, 0,
	101, 0, 0, 0, 0, 71, 344, 0, 84, 86,
	74, 75, 76, 77, 78, 0, 0, 0, 0, 100,
	0, 70, 0, 73, 0, 0, 98, 96, 102, 82,
	83, 85, 87, 97, 99, 0, 0, 0, 0, 72,
	0, 0, 0, 0, 88, 89, 90, 91, 92, 93,
	0, 0, 94, 95, 79, 80, 81, 0, 0, 0,
	0, 0, 0, 0, 101, 0, 0, 0, 0, 71,
	337, 0, 84, 86, 74, 75, 76, 77, 78, 0,
	0, 0, 0, 100, 0, 70, 0, 73, 0, 0,
	98, 96, 102, 82, 83, 85, 87, 97, 99, 0,
	0, 0, 0, 72, 0, 0, 0, 0, 88, 89,
	90, 91, 92, 93, 0, 0, 94, 95, 79, 80,
	81, 0, 0, 0, 0, 0, 0, 0, 101, 0,
	0, 0, 0, 71, 0, 0, 84, 86, 74, 75,
	76, 77, 78, 0, 332, 0, 0, 100, 0, 70,
	0, 73, 0, 0, 98, 96, 102, 82, 83, 85,
	87, 97, 99, 0, 0, 0, 0, 72, 0, 0,
	0, 0, 88, 89, 90, 91, 92, 93, 0, 0,
	94, 95, 79, 80, 81, 0, 0, 0, 0, 0,
	0, 0, 101, 0, 0, 0, 0, 71, 0, 0,
	84, 86, 74, 75, 76, 77, 78, 0, 0, 0,
	0, 100, 329, 70, 0, 73, 0, 0, 98, 96,
	102, 82, 83, 85, 87, 97, 99, 0, 0, 0,
	0, 72, 0, 0, 0, 0, 88, 89, 90, 91,
	92, 93, 0, 0, 94, 95, 79, 80, 81, 0,
	0, 0, 0, 0, 0, 0, 101, 0, 0, 0,
	0, 71, 0, 0, 84, 86, 74, 75, 76, 77,
	78, 0, 0, 0, 0, 100, 0, 70, 320, 73,
	0, 0, 98, 96, 102, 82, 83, 85, 87, 97,
	99, 0, 0, 0, 0, 72, 0, 0, 0, 0,
	88, 89, 90, 91, 92, 93, 0, 0, 94, 95,
	79, 80, 81, 0, 0, 0, 0, 0, 0, 0,
	101, 0, 0, 0, 0, 71, 0, 0, 84, 86,
	74, 75, 76, 77, 78, 0, 0, 0, 0, 100,
	0, 70, 310, 73, 0, 0, 98, 96, 102, 82,
	83, 85, 87, 97, 99, 0, 0, 0, 0, 72,
	0, 0, 0, 0, 88, 89, 90, 91, 92, 93,
	0, 0, 94, 95, 79, 80, 81, 0, 0, 0,
	0, 0, 0, 0, 101, 0, 0, 0, 0, 71,
	0, 0, 84, 86, 74, 75, 76, 77, 78, 0,
	0, 0, 0, 100, 0, 70, 284, 73, 0, 0,
	98, 96, 102, 82, 83, 85, 87, 97, 99, 0,
	0, 0, 0, 72, 0, 0, 0, 0, 88, 89,
	90, 91, 92, 93, 0, 0, 94, 95, 79, 80,
	81, 0, 0, 0, 0, 0, 0, 0, 101, 0,
	0, 0, 0, 71, 0, 0, 84, 86, 74, 75,
	76, 77, 78, 0, 0, 0, 0, 100, 0, 70,
	268, 73, 0, 0, 98, 96, 102, 82, 83, 85,
	87, 97, 99, 0, 0, 0, 0, 72, 0, 0,
	0, 0, 88, 89, 90, 91, 92, 93, 0, 0,
	94, 95, 79, 80, 81, 0, 0, 0, 0, 0,
	0, 0, 101, 0, 0, 0, 0, 71, 0, 0,
	84, 86, 74, 75, 76, 77, 78, 0, 0, 0,
	259, 100, 0, 70, 0, 73, 0, 0, 98, 96,
	102, 82, 83, 85, 87, 97, 99, 0, 0, 0,
	0, 72, 0, 0, 0, 0, 88, 89, 90, 91,
	92, 93, 0, 0, 94, 95, 79, 80, 81, 0,
	0, 0, 0, 0, 0, 0, 101, 0, 0, 0,
	0, 71, 0, 0, 84, 86, 74, 75, 76, 77,
	78, 0, 257, 0, 0, 100, 0, 70, 0, 73,
	0, 0, 98, 96, 102, 82, 83, 85, 87, 97,
	99, 0, 0, 0, 0, 72, 0, 0, 0, 0,
	88, 89, 90, 91, 92, 93, 0, 0, 94, 95,
	79, 80, 81, 0, 0, 0, 0, 0, 0, 0,
	101, 0, 0, 0, 0, 71, 0, 0, 84, 86,
	74, 75, 76, 77, 78, 0, 255, 0, 0, 100,
	0, 70, 0, 73, 0, 0, 98, 96, 102, 82,
	83, 85, 87, 97, 99, 0, 0, 0, 0, 72,
	0, 0, 0, 0, 88, 89, 90, 91, 92, 93,
	0, 0, 94, 95, 79, 80, 81, 0, 0, 0,
	0, 0, 0, 0, 101, 0, 0, 0, 0, 71,
	0, 0, 84, 86, 74, 75, 76, 77, 78, 0,
	0, 0, 0, 100, 241, 70, 0, 73, 0, 0,
	98, 96, 102, 82, 83, 85, 87, 97, 99, 0,
	0, 0, 0, 72, 0, 0, 0, 0, 88, 89,
	90, 91, 92, 93, 0, 0, 94, 95, 79, 80,
	81, 0, 0, 0, 0, 0, 0, 0, 101, 0,
	0, 0, 0, 71, 238, 0, 84, 86, 74, 75,
	76, 77, 78, 0, 0, 0, 0, 100, 0, 70,
	0, 73, 0, 0, 98, 96, 102, 82, 83, 85,
	87, 97, 99, 0, 0, 0, 0, 72, 0, 0,
	0, 0, 88, 89, 90, 91, 92, 93, 0, 0,
	94, 95, 79, 80, 81, 0, 0, 0, 0, 0,
	0, 0, 101, 0, 0, 0, 0, 71, 215, 0,
	84, 86, 74, 75, 76, 77, 78, 0, 0, 0,
	0, 100, 0, 70, 0, 73, 0, 0, 98, 96,
	102, 82, 83, 85, 87, 97, 99, 0, 0, 0,
	0, 72, 0, 0, 0, 0, 88, 89, 90, 91,
	92, 93, 0, 0, 94, 95, 79, 80, 81, 0,
	0, 0, 0, 0, 0, 0, 101, 0, 0, 0,
	0, 71, 0, 0, 84, 86, 74, 75, 76, 77,
	78, 0, 0, 0, 0, 100, 188, 70, 0, 73,
	0, 0, 98, 96, 102, 82, 83, 85, 87, 97,
	99, 0, 0, 0, 0, 72, 0, 0, 0, 0,
	88, 89, 90, 91, 92, 93, 0, 0, 94, 95,
	79, 80, 81, 0, 0, 0, 0, 0, 0, 0,
	101, 0, 0, 0, 0, 71, 0, 0, 84, 86,
	74, 75, 76, 77, 78, 0, 177, 0, 0, 100,
	0, 70, 0, 73, 0, 0, 98, 96, 102, 82,
	83, 85, 87, 97, 99, 0, 0, 0, 0, 72,
	0, 0, 0, 0, 88, 89, 90, 91, 92, 93,
	0, 0, 94, 95, 79, 80, 81, 0, 0, 0,
	0, 0, 0, 0, 101, 0, 0, 0, 0, 71,
	0, 0, 84, 86, 74, 75, 76, 77, 78, 0,
	176, 0, 0, 100, 0, 70, 0, 73, 0, 0,
	98, 96, 102, 82, 83, 85, 87, 97, 99, 0,
	0, 0, 0, 72, 0, 0, 0, 0, 88, 89,
	90, 91, 92, 93, 0, 0, 94, 95, 79, 80,
	81, 0, 0, 0, 0, 0, 0, 0, 101, 0,
	0, 0, 69, 71, 0, 0, 84, 86, 74, 75,
	76, 77, 78, 0, 0, 0, 0, 100, 0, 70,
	0, 73, 0, 0, 98, 96, 102, 82, 83, 85,
	87, 97, 99, 0, 0, 0, 0, 72, 0, 0,
	0, 0, 88, 89, 90, 91, 92, 93, 0, 0,
	94, 95, 79, 80, 81, 0, 0, 0, 0, 0,
	0, 0, 101, 0, 0, 0, 0, 71, 0, 0,
	84, 86, 74, 75, 76, 77, 78, 0, 0, 0,
	0, 100, 0, 70, 0, 73, 0, 0, 98, 96,
	102, 82, 83, 85, 87, 97, 99, 0, 0, 0,
	0, 72, 0, 0, 0, 0, 88, 89, 90, 91,
	92, 93, 0, 0, 94, 95, 79, 80, 81, 0,
	0, 0, 0, 0, 0, 0, 101, 0, 0, 0,
	0, 71, 0, 0, 84, 86, 74, 75, 76, 77,
	78, 0, 0, 0, 0, 100, 0, 70, 0, 182,
	0, 0, 98, 96, 102, 82, 83, 85, 87, 97,
	99, 0, 0, 0, 0, 72, 0, 0, 0, 0,
	88, 89, 90, 91, 92, 93, 0, 0, 94, 95,
	79, 80, 81, 0, 0, 0, 0, 0, 0, 0,
	101, 0, 0, 0, 0, 71, 0, 0, 84, 86,
	74, 75, 76, 77, 78, 0, 0, 0, 0, 100,
	0, 70, 0, 181, 0, 0, 98, 96, 102, 82,
	83, 85, 87, 97, 99, 0, 0, 0, 0, 72,
	0, 0, 0, 0, 88, 89, 90, 91, 92, 93,
	0, 0, 94, 95, 79, 80, 81, 0, 0, 0,
	0, 0, 0, 0, 101, 0, 0, 0, 0, 71,
	0, 0, 84, 86, 74, 75, 76, 77, 78, 0,
	0, 0, 0, 142, 0, 70, 0, 73, 0, 0,
	98, 96, 102, 82, 83, 85, 87, 97, 99, 0,
	0, 0, 0, 72, 0, 0, 0, 0, 88, 89,
	90, 91, 92, 93, 0, 0, 94, 95, 79, 80,
	81, 0, 0, 0, 0, 0, 0, 0, 101, 0,
	0, 0, 0, 0, 0, 0, 84, 86, 74, 75,
	76, 77, 78, 0, 0, 0, 0, 100, 0, 70,
	0, 73, 0, 0, 98, 96, 43, 29, 35, 0,
	0, 39, 13, 50, 14, 25, 0, 17, 0, 0,
	0, 0, 0, 0, 0, 46, 36, 37, 38, 0,
	15, 18, 0, 0, 0, 0, 0, 0, 0, 0,
	11, 12, 0, 0, 0, 0, 0, 26, 27, 0,
	0, 21, 0, 47, 48, 0, 45, 49, 0, 0,
	0, 0, 0, 0, 0, 30, 34, 0, 0, 0,
	41, 0, 0, 42, 0, 40, 0, 0, 31, 32,
	33, 102, 82, 83, 85, 87, 0, 99, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 88, 89, 90,
	91, 92, 93, 0, 0, 94, 95, 79, 80, 81,
	0, 0, 0, 0, 0, 0, 0, 101, 0, 0,
	0, 0, 0, 0, 0, 84, 86, 74, 75, 76,
	77, 78, 0, 0, 0, 0, 100, 0, 70, 0,
	73, 0, 0, 98, 96, 102, 82, 83, 85, 87,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 88, 89, 90, 91, 92, 93, 0, 0, 94,
	95, 79, 80, 81, 0, 0, 0, 0, 0, 0,
	0, 101, 0, 0, 0, 0, 0, 0, 0, 84,
	86, 74, 75, 76, 77, 78, 85, 87, 0, 0,
	100, 0, 70, 0, 73, 0, 0, 98, 96, 88,
	89, 90, 91, 92, 93, 0, 0, 94, 95, 79,
	80, 81, 0, 0, 0, 43, 29, 35, 0, 101,
	39, 0, 0, 0, 0, 0, 0, 84, 86, 74,
	75, 76, 77, 78, 46, 36, 37, 38, 100, 0,
	70, 0, 73, 0, 0, 98, 96, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 47, 48, 0, 45, 49, 0, 0, 0,
	0, 0, 0, 0, 30, 34, 0, 0, 0, 41,
	0, 0, 42, 0, 40, 267, 0, 31, 32, 33,
	88, 89, 90, 91, 92, 93, 0, 0, 94, 95,
	79, 0, 0, 0, 0, 0, 43, 29, 35, 0,
	101, 39, 0, 0, 0, 0, 0, 0, 0, 0,
	74, 75, 76, 77, 78, 46, 36, 37, 38, 100,
	0, 70, 0, 73, 0, 0, 98, 96, 0, 0,
	0, 0, 43, 29, 35, 0, 0, 39, 0, 0,
	0, 0, 0, 47, 48, 0, 45, 49, 0, 0,
	180, 46, 36, 37, 38, 30, 34, 0, 0, 0,
	41, 0, 0, 42, 0, 40, 0, 0, 31, 32,
	33, 0, 0, 0, 0, 0, 0, 0, 0, 47,
	48, 0, 45, 49, 0, 0, 145, 0, 65, 29,
	35, 30, 34, 39, 0, 50, 41, 0, 0, 42,
	0, 40, 0, 0, 31, 32, 33, 46, 36, 37,
	38, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 43, 29, 35, 0, 0, 39, 0, 0, 0,
	0, 0, 0, 0, 0, 47, 48, 0, 45, 49,
	46, 36, 37, 38, 0, 0, 0, 30, 34, 0,
	0, 0, 61, 0, 0, 42, 0, 40, 0, 0,
	31, 32, 33, 0, 0, 0, 0, 0, 47, 48,
	0, 45, 49, 0, 0, 0, 0, 67, 29, 35,
	30, 34, 39, 0, 0, 41, 0, 0, 42, 0,
	40, 0, 0, 31, 32, 33, 46, 36, 37, 38,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 47, 48, 0, 45, 49, 0,
	0, 0, 0, 0, 0, 0, 30, 34, 0, 0,
	0, 41, 0, 0, 42, 0, 40, 0, 0, 31,
	32, 33, 88, 89, 90, 91, 92, 93, 0, 0,
	0, 0, 79, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 101, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 76, 77, 78, 0, 0, 0,
	0, 100, 0, 70, 0, 73, 0, 0, 98, 96,
}
var yyPact = [...]int{

	-59, -1000, 2382, -59, -1000, -63, -63, -1000, -1000, -1000,
	-1000, -1000, -1000, 2817, 2817, 259, 228, 2784, 126, -1000,
	-1000, 2873, 1986, -1000, -1000, 2817, 2817, 124, -32, -1000,
	2817, 2817, 2817, 2817, 2817, -1000, -1000, -1000, -1000, 64,
	-63, -63, 2817, 25, -1000, 49, 43, 39, 2817, 30,
	249, 150, -1000, 2382, -63, -1000, 139, 2050, 2050, 123,
	165, -59, 187, 51, 642, 25, -59, 24, 2242, 2817,
	2728, 2817, 2817, 258, 2817, 2817, 2817, 2817, 2817, 2817,
	2817, 2817, 2817, 2817, 2817, 2817, 2817, 2817, 2817, 2817,
	2817, 2817, 2817, 2817, -1000, -1000, 2817, 2817, 2817, 2817,
	2817, 2817, 2817, 1922, 1858, -63, 2692, 186, 186, 186,
	-32, 2178, -32, 2114, 249, -23, 2817, -63, 2817, 1794,
	2817, 2817, 248, 55, 2050, 2817, 141, -1000, 2817, -63,
	-1000, -59, 2817, -59, 102, -63, 2817, -63, 2817, -59,
	100, 2817, 2817, 2050, 578, 2817, 1730, 2306, -1000, 2920,
	2920, 186, 186, 186, 2050, 2648, 2648, 2557, 2557, 2648,
	2648, 2648, 2648, 2050, 2050, 2050, 2050, 2050, 2050, 2050,
	2445, 2050, 2509, 107, 2050, 2509, -59, -63, 188, 514,
	2817, 251, 250, 105, 249, -34, -43, 1666, -1000, 103,
	1602, -13, -1000, 248, 36, 246, -38, 450, 2817, 139,
	2817, 94, 1538, 89, -1000, 1474, 245, 1410, 87, 207,
	98, 96, 2601, -1000, 1346, 2817, -5, -1000, 85, 167,
	-24, -1000, -1000, 153, 2382, 264, -1000, 1282, -1000, -1000,
	121, -8, 66, -63, -44, -63, -63, 83, 2817, -9,
	-1000, -1000, 241, -1000, -6, -46, -30, 143, -1000, -1000,
	2817, 139, 2050, -32, -1000, -59, -1000, -59, -1000, 2817,
	-1000, 149, -15, -1000, -17, -1000, 1218, -1000, -1000, 2050,
	-1000, -1000, -28, -1000, -1000, 152, 2817, 82, -1000, -1000,
	-59, 146, 1154, -1000, -1000, -59, 117, 115, -25, -63,
	-1000, 2817, -1000, 2050, -1000, -1000, -1000, 2817, -1000, -1000,
	2817, 2817, 1090, 81, 80, 1026, 108, -59, -1000, -1000,
	-1000, 78, -1000, -1000, -59, 962, 137, -1000, -1000, -59,
	-1000, 75, -59, -59, 106, 898, 834, 386, 770, -1000,
	-1000, -1000, -59, -59, 74, -1000, -1000, -59, -59, -1000,
	-1000, 73, 67, -59, 2817, -1000, -1000, 2817, -1000, 65,
	63, 203, -1000, -1000, -1000, -1000, 62, 2050, 706, -1000,
	181, 104, -1000, -1000, 99, -59, -59, 61, 58, -1000,
	-1000,
}
var yyPgo = [...]int{

	0, 50, 293, 7, 240, 291, 286, 285, 284, 282,
	2, 1, 281, 280, 9, 8, 0, 44, 279, 14,
	13, 278, 266, 4, 272, 267, 10, 6, 118, 5,
}
var yyR1 = [...]int{

	0, 1, 1, 2, 2, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 4, 4,
	5, 6, 6, 7, 7, 7, 12, 13, 13, 13,
	13, 13, 14, 15, 8, 9, 9, 9, 9, 9,
	10, 10, 11, 21, 21, 21, 18, 18, 18, 19,
	19, 19, 20, 20, 17, 17, 17, 17, 22, 22,
	22, 22, 22, 22, 16, 16, 16, 16, 16, 16,
	16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
	16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
	16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
	16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
	16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
	16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
	16, 16, 16, 23, 24, 24, 25, 25, 25, 26,
	26, 28, 28, 29, 27, 27, 27, 27,
}
var yyR2 = [...]int{

	0, 1, 2, 2, 3, 0, 1, 1, 1, 2,
	2, 5, 1, 4, 7, 9, 5, 13, 12, 9,
	8, 1, 1, 6, 5, 6, 5, 1, 1, 1,
	4, 3, 3, 5, 7, 5, 6, 0, 1, 1,
	2, 2, 4, 3, 7, 0, 1, 1, 2, 2,
	4, 4, 3, 0, 2, 3, 0, 3, 6, 0,
	1, 4, 1, 3, 0, 1, 4, 4, 6, 5,
	5, 6, 5, 5, 1, 1, 2, 2, 2, 2,
	4, 2, 4, 1, 1, 1, 1, 5, 3, 3,
	7, 8, 8, 9, 5, 5, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 2, 2, 3,
	3, 3, 3, 5, 4, 5, 4, 4, 4, 1,
	4, 4, 5, 7, 5, 7, 9, 7, 3, 2,
	4, 6, 3, 1, 0, 1, 2, 1, 1, 0,
	1, 1, 2, 1, 0, 2, 1, 1,
}
var yyChk = [...]int{

	-1000, -1, -24, -2, -25, 70, -28, -29, 80, -3,
	-4, 38, 39, 10, 12, 28, -7, 15, 29, -8,
	-12, 49, -16, -5, -6, 13, 45, 46, -23, 5,
	63, 76, 77, 78, 64, 6, 24, 25, 26, 9,
	73, 68, 71, 4, -22, 54, 23, 51, 52, 55,
	11, -17, -24, -25, -28, -29, -17, -16, -16, 4,
	14, 68, -19, -4, -16, 4, 68, 4, -16, 56,
	73, 57, 27, 75, 62, 63, 64, 65, 66, 42,
	43, 44, 17, 18, 60, 19, 61, 20, 32, 33,
	34, 35, 36, 37, 40, 41, 79, 21, 78, 22,
	71, 52, 16, -16, -16, 68, 73, -16, -16, -16,
	-23, -16, -23, -16, 71, 4, -26, -28, -26, -16,
	71, 71, 71, 71, -16, 71, -19, 4, 56, 59,
	-3, 68, 13, 68, -1, -28, 16, 59, 70, 68,
	-1, 71, 71, -16, -16, 58, -16, -16, 4, -16,
	-16, -16, -16, -16, -16, -16, -16, -16, -16, -16,
	-16, -16, -16, -16, -16, -16, -16, -16, -16, -16,
	-16, -16, -16, -17, -16, -16, 68, 68, -26, -16,
	58, 75, 75, -19, 71, -17, -18, -16, 72, -17,
	-16, -20, 4, 50, -21, 53, 73, -16, 56, -17,
	-26, -1, -16, -1, 69, -16, -26, -16, -1, 69,
	-17, -17, 58, 74, -16, 58, 8, 72, -1, -26,
	-13, -15, -14, 48, 47, 58, 74, -16, 4, 4,
	72, 8, -19, 59, -27, -28, 59, -27, 58, 8,
	72, 72, 75, 72, -20, 73, -20, 4, 74, 72,
	59, -17, -16, -23, 69, 68, 69, 68, 4, 70,
	69, 30, 8, 72, 8, 72, -16, 74, 74, -16,
	72, 69, -9, -11, -10, 48, 47, -26, -14, -15,
	58, -3, -16, 74, 74, 68, 72, 72, 8, -28,
	74, -26, 69, -16, 72, 4, 72, 59, 74, 72,
	59, 59, -16, -1, -1, -16, 4, 68, 72, 72,
	74, -26, -10, -11, 58, -16, -17, 69, -1, 58,
	74, -1, 68, 68, 72, -16, -16, -16, -16, 72,
	69, 69, 68, 68, -1, 69, -1, 58, 58, -1,
	69, -1, -1, 68, 58, 72, 72, 59, 72, -1,
	-1, 69, -1, -1, 69, 69, -1, -16, -16, 69,
	69, 31, 69, 72, 31, 68, 68, -1, -1, 69,
	69,
}
var yyDef = [...]int{

	144, -2, -2, 144, 145, 148, 147, 151, 153, 3,
	6, 7, 8, 64, 0, 0, 12, -2, 0, 21,
	22, 0, -2, 28, 29, 0, 0, 0, 74, 75,
	0, 0, 0, 0, 0, 83, 84, 85, 86, 0,
	149, 149, 0, 143, 129, 0, 0, 0, 0, 0,
	59, 0, 2, -2, 146, 152, 9, 65, 10, 0,
	0, 144, 0, 0, 65, -2, 144, 143, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 117, 118, 0, 0, 0, 0,
	64, 0, 0, 0, 0, 149, 0, 76, 77, 78,
	-2, 0, -2, 0, 59, 0, 64, 150, 56, 0,
	64, 0, 0, 53, 139, 0, 0, 60, 64, 149,
	4, 144, 0, 144, 0, 147, 0, 149, 0, 144,
	0, 64, 64, 31, 0, 0, 0, 88, 89, 97,
	98, 99, 100, 101, 102, 103, 104, -2, -2, 107,
	108, 109, 110, 111, 112, 113, 114, 115, 116, 119,
	120, 121, 122, 0, 138, 142, 144, 149, 37, 0,
	0, 0, 0, 0, 59, 154, 154, 0, 96, 0,
	0, 0, 62, 0, 0, 0, 0, 0, 64, 32,
	0, 0, 0, 0, 13, 0, 0, 0, 0, 0,
	0, 0, 0, 128, 0, 0, 0, 126, 0, 45,
	149, 38, 39, 0, -2, 0, 127, 0, 80, 82,
	0, 0, 0, -2, 0, 156, -2, 0, 0, 0,
	124, 130, 0, 131, 0, 0, 0, 0, 54, 140,
	0, 30, 66, -2, 11, 144, 35, 144, 61, 0,
	16, 0, 0, -2, 0, -2, 0, 72, 73, 87,
	125, 33, 149, 46, 47, 0, 64, 0, 40, 41,
	144, 0, 0, 69, 70, 144, 0, 0, 0, -2,
	94, 0, 95, 57, 123, 63, 132, 0, 55, 134,
	0, 0, 0, 0, 0, 0, 0, 144, -2, -2,
	71, 0, 48, 49, 144, 65, 0, 36, 43, 144,
	68, 0, 144, 144, 0, 0, 0, 0, 0, 141,
	34, 14, 144, 144, 0, 44, 52, 144, 144, 42,
	90, 0, 0, 144, 0, 133, 135, 0, 137, 0,
	0, 20, 50, 51, 91, 92, 0, 58, 0, 15,
	19, 0, 93, 136, 0, 144, 144, 0, 0, 18,
	17,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	80, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 76, 3, 3, 3, 66, 78, 3,
	71, 72, 64, 62, 59, 63, 75, 65, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 58, 70,
	61, 56, 60, 57, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 73, 3, 74, 77, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 68, 79, 69,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 67,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:81
		{
			yyVAL.compstmt = nil
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:85
		{
			yyVAL.compstmt = yyDollar[1].stmts
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:91
		{
			if yyDollar[2].stmt != nil {
				yyVAL.stmts = []ast.Stmt{yyDollar[2].stmt}
			} else {
				yyVAL.stmts = []ast.Stmt{}
			}
			if l, ok := yylex.(*Lexer); ok {
				l.stmts = yyVAL.stmts
			}
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:102
		{
			if yyDollar[3].stmt != nil {
				yyVAL.stmts = append(yyDollar[1].stmts, yyDollar[3].stmt)
				if l, ok := yylex.(*Lexer); ok {
					l.stmts = yyVAL.stmts
				}
			}
		}
	case 5:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:113
		{
			yyVAL.stmt = nil
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:117
		{
			yyVAL.stmt = yyDollar[1].stmt_var_or_lets
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:121
		{
			yyVAL.stmt = &ast.BreakStmt{}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:126
		{
			yyVAL.stmt = &ast.ContinueStmt{}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:131
		{
			yyVAL.stmt = &ast.ReturnStmt{Exprs: yyDollar[2].exprs}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:136
		{
			yyVAL.stmt = &ast.ThrowStmt{Expr: yyDollar[2].expr}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 11:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:141
		{
			yyVAL.stmt = &ast.ModuleStmt{Name: yyDollar[2].tok.Lit, Stmts: yyDollar[4].compstmt}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:146
		{
			yyVAL.stmt = yyDollar[1].stmt_if
			yyVAL.stmt.SetPosition(yyDollar[1].stmt_if.Position())
		}
	case 13:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:151
		{
			yyVAL.stmt = &ast.LoopStmt{Stmts: yyDollar[3].compstmt}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 14:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:156
		{
			yyVAL.stmt = &ast.ForStmt{Vars: yyDollar[2].expr_idents, Value: yyDollar[4].expr, Stmts: yyDollar[6].compstmt}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 15:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser.go.y:161
		{
			yyVAL.stmt = &ast.CForStmt{Stmt1: yyDollar[2].stmt_var_or_lets, Expr2: yyDollar[4].expr, Expr3: yyDollar[6].expr, Stmts: yyDollar[8].compstmt}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 16:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:166
		{
			yyVAL.stmt = &ast.LoopStmt{Expr: yyDollar[2].expr, Stmts: yyDollar[4].compstmt}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 17:
		yyDollar = yyS[yypt-13 : yypt+1]
//line parser.go.y:171
		{
			yyVAL.stmt = &ast.TryStmt{Try: yyDollar[3].compstmt, Var: yyDollar[6].tok.Lit, Catch: yyDollar[8].compstmt, Finally: yyDollar[12].compstmt}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 18:
		yyDollar = yyS[yypt-12 : yypt+1]
//line parser.go.y:176
		{
			yyVAL.stmt = &ast.TryStmt{Try: yyDollar[3].compstmt, Catch: yyDollar[7].compstmt, Finally: yyDollar[11].compstmt}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 19:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser.go.y:181
		{
			yyVAL.stmt = &ast.TryStmt{Try: yyDollar[3].compstmt, Var: yyDollar[6].tok.Lit, Catch: yyDollar[8].compstmt}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 20:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:186
		{
			yyVAL.stmt = &ast.TryStmt{Try: yyDollar[3].compstmt, Catch: yyDollar[7].compstmt}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:191
		{
			yyVAL.stmt = yyDollar[1].stmt_switch
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:195
		{
			yyVAL.stmt = yyDollar[1].stmt_select
		}
	case 23:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:199
		{
			yyVAL.stmt = &ast.GoroutineStmt{Expr: &ast.CallExpr{Name: yyDollar[2].tok.Lit, SubExprs: yyDollar[4].exprs, VarArg: true, Go: true}}
			yyVAL.stmt.SetPosition(yyDollar[2].tok.Position())
		}
	case 24:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:204
		{
			yyVAL.stmt = &ast.GoroutineStmt{Expr: &ast.CallExpr{Name: yyDollar[2].tok.Lit, SubExprs: yyDollar[4].exprs, Go: true}}
			yyVAL.stmt.SetPosition(yyDollar[2].tok.Position())
		}
	case 25:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:209
		{
			yyVAL.stmt = &ast.GoroutineStmt{Expr: &ast.AnonCallExpr{Expr: yyDollar[2].expr, SubExprs: yyDollar[4].exprs, VarArg: true, Go: true}}
			yyVAL.stmt.SetPosition(yyDollar[2].expr.Position())
		}
	case 26:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:214
		{
			yyVAL.stmt = &ast.GoroutineStmt{Expr: &ast.AnonCallExpr{Expr: yyDollar[2].expr, SubExprs: yyDollar[4].exprs, Go: true}}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:219
		{
			yyVAL.stmt = &ast.ExprStmt{Expr: yyDollar[1].expr}
			yyVAL.stmt.SetPosition(yyDollar[1].expr.Position())
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:226
		{
			yyVAL.stmt_var_or_lets = yyDollar[1].stmt_var
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:230
		{
			yyVAL.stmt_var_or_lets = yyDollar[1].stmt_lets
		}
	case 30:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:236
		{
			yyVAL.stmt_var = &ast.VarStmt{Names: yyDollar[2].expr_idents, Exprs: yyDollar[4].exprs}
			yyVAL.stmt_var.SetPosition(yyDollar[1].tok.Position())
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:243
		{
			yyVAL.stmt_lets = &ast.LetsStmt{Lhss: []ast.Expr{yyDollar[1].expr}, Operator: "=", Rhss: []ast.Expr{yyDollar[3].expr}}
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:247
		{
			if len(yyDollar[1].exprs) == 2 && len(yyDollar[3].exprs) == 1 {
				if _, ok := yyDollar[3].exprs[0].(*ast.ItemExpr); ok {
					yyVAL.stmt_lets = &ast.LetMapItemStmt{Lhss: yyDollar[1].exprs, Rhs: yyDollar[3].exprs[0]}
				} else {
					yyVAL.stmt_lets = &ast.LetsStmt{Lhss: yyDollar[1].exprs, Operator: "=", Rhss: yyDollar[3].exprs}
				}
			} else {
				yyVAL.stmt_lets = &ast.LetsStmt{Lhss: yyDollar[1].exprs, Operator: "=", Rhss: yyDollar[3].exprs}
			}
		}
	case 33:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:261
		{
			yyVAL.stmt_if = &ast.IfStmt{If: yyDollar[2].expr, Then: yyDollar[4].compstmt, Else: nil}
			yyVAL.stmt_if.SetPosition(yyDollar[1].tok.Position())
		}
	case 34:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:266
		{
			yyDollar[1].stmt_if.(*ast.IfStmt).ElseIf = append(yyDollar[1].stmt_if.(*ast.IfStmt).ElseIf, &ast.IfStmt{If: yyDollar[4].expr, Then: yyDollar[6].compstmt})
			yyVAL.stmt_if.SetPosition(yyDollar[1].stmt_if.Position())
		}
	case 35:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:271
		{
			yyVAL.stmt_if.SetPosition(yyDollar[1].stmt_if.Position())
			if yyVAL.stmt_if.(*ast.IfStmt).Else != nil {
				yylex.Error("multiple else statement")
			} else {
				yyVAL.stmt_if.(*ast.IfStmt).Else = yyDollar[4].compstmt
			}
		}
	case 36:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:282
		{
			yyVAL.stmt_select = &ast.SelectStmt{Body: yyDollar[4].stmt_select_cases}
			yyVAL.stmt_select.SetPosition(yyDollar[1].tok.Position())
		}
	case 37:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:289
		{
			yyVAL.stmt_select_cases = &ast.SelectBodyStmt{}
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:293
		{
			yyVAL.stmt_select_cases = &ast.SelectBodyStmt{Default: yyDollar[1].stmt_select_default}
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:297
		{
			yyVAL.stmt_select_cases = &ast.SelectBodyStmt{Cases: []ast.Stmt{yyDollar[1].stmt_select_case}}
		}
	case 40:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:301
		{
			body := yyVAL.stmt_select_cases.(*ast.SelectBodyStmt)
			body.Cases = append(body.Cases, yyDollar[2].stmt_select_case)
		}
	case 41:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:306
		{
			body := yyVAL.stmt_select_cases.(*ast.SelectBodyStmt)
			if body.Default != nil {
				yylex.Error("multiple default statement")
			}
			body.Default = yyDollar[2].stmt_select_default
		}
	case 42:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:317
		{
			yyVAL.stmt_select_case = &ast.SelectCaseStmt{Expr: yyDollar[2].stmt, Stmts: yyDollar[4].compstmt}
			yyVAL.stmt_select_case.SetPosition(yyDollar[1].tok.Position())
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:324
		{
			yyVAL.stmt_select_default = yyDollar[3].compstmt
		}
	case 44:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:330
		{
			yyVAL.stmt_switch = &ast.SwitchStmt{Expr: yyDollar[2].expr, Body: yyDollar[5].stmt_switch_cases}
			yyVAL.stmt_switch.SetPosition(yyDollar[1].tok.Position())
		}
	case 45:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:337
		{
			yyVAL.stmt_switch_cases = &ast.SwitchBodyStmt{}
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:341
		{
			yyVAL.stmt_switch_cases = &ast.SwitchBodyStmt{Default: yyDollar[1].stmt_switch_default}
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:345
		{
			yyVAL.stmt_switch_cases = &ast.SwitchBodyStmt{Cases: []ast.Stmt{yyDollar[1].stmt_switch_case}}
		}
	case 48:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:349
		{
			body := yyVAL.stmt_switch_cases.(*ast.SwitchBodyStmt)
			body.Cases = append(body.Cases, yyDollar[2].stmt_switch_case)
		}
	case 49:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:354
		{
			body := yyVAL.stmt_switch_cases.(*ast.SwitchBodyStmt)
			if body.Default != nil {
				yylex.Error("multiple default statement")
			}
			body.Default = yyDollar[2].stmt_switch_default
		}
	case 50:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:365
		{
			yyVAL.stmt_switch_case = &ast.SwitchCaseStmt{Exprs: []ast.Expr{yyDollar[2].expr}, Stmts: yyDollar[4].compstmt}
			yyVAL.stmt_switch_case.SetPosition(yyDollar[1].tok.Position())
		}
	case 51:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:370
		{
			yyVAL.stmt_switch_case = &ast.SwitchCaseStmt{Exprs: yyDollar[2].exprs, Stmts: yyDollar[4].compstmt}
			yyVAL.stmt_switch_case.SetPosition(yyDollar[1].tok.Position())
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:377
		{
			yyVAL.stmt_switch_default = yyDollar[3].compstmt
		}
	case 53:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:382
		{
			yyVAL.array_count = ast.ArrayCount{Count: 0}
		}
	case 54:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:386
		{
			yyVAL.array_count = ast.ArrayCount{Count: 1}
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:390
		{
			yyVAL.array_count.Count = yyVAL.array_count.Count + 1
		}
	case 56:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:395
		{
			yyVAL.map_expr = make(map[ast.Expr]ast.Expr)
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:399
		{
			mapExpr := make(map[ast.Expr]ast.Expr)
			mapExpr[yyDollar[1].expr] = yyDollar[3].expr
			yyVAL.map_expr = mapExpr
		}
	case 58:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:405
		{
			if len(yyDollar[1].map_expr) == 0 {
				yylex.Error("syntax error: unexpected ','")
			}
			yyDollar[1].map_expr[yyDollar[4].expr] = yyDollar[6].expr
		}
	case 59:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:413
		{
			yyVAL.expr_idents = []string{}
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:417
		{
			yyVAL.expr_idents = []string{yyDollar[1].tok.Lit}
		}
	case 61:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:421
		{
			if len(yyDollar[1].expr_idents) == 0 {
				yylex.Error("syntax error: unexpected ','")
			}
			yyVAL.expr_idents = append(yyDollar[1].expr_idents, yyDollar[4].tok.Lit)
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:430
		{
			yyVAL.expr_type = yyDollar[1].tok.Lit
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:434
		{
			yyVAL.expr_type = yyVAL.expr_type + "." + yyDollar[3].tok.Lit
		}
	case 64:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:439
		{
			yyVAL.exprs = nil
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:443
		{
			yyVAL.exprs = []ast.Expr{yyDollar[1].expr}
		}
	case 66:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:447
		{
			if len(yyDollar[1].exprs) == 0 {
				yylex.Error("syntax error: unexpected ','")
			}
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[4].expr)
		}
	case 67:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:454
		{
			if len(yyDollar[1].exprs) == 0 {
				yylex.Error("syntax error: unexpected ','")
			}
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[4].expr_ident)
		}
	case 68:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:463
		{
			yyVAL.expr_slice = &ast.SliceExpr{Value: yyDollar[1].expr_ident, Begin: yyDollar[3].expr, End: yyDollar[5].expr}
		}
	case 69:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:467
		{
			yyVAL.expr_slice = &ast.SliceExpr{Value: yyDollar[1].expr_ident, Begin: yyDollar[3].expr, End: nil}
		}
	case 70:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:471
		{
			yyVAL.expr_slice = &ast.SliceExpr{Value: yyDollar[1].expr_ident, Begin: nil, End: yyDollar[4].expr}
		}
	case 71:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:475
		{
			yyVAL.expr_slice = &ast.SliceExpr{Value: yyDollar[1].expr, Begin: yyDollar[3].expr, End: yyDollar[5].expr}
		}
	case 72:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:479
		{
			yyVAL.expr_slice = &ast.SliceExpr{Value: yyDollar[1].expr, Begin: yyDollar[3].expr, End: nil}
		}
	case 73:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:483
		{
			yyVAL.expr_slice = &ast.SliceExpr{Value: yyDollar[1].expr, Begin: nil, End: yyDollar[4].expr}
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:489
		{
			yyVAL.expr = yyDollar[1].expr_ident
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:493
		{
			yyVAL.expr = &ast.NumberExpr{Lit: yyDollar[1].tok.Lit}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 76:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:498
		{
			yyVAL.expr = &ast.UnaryExpr{Operator: "-", Expr: yyDollar[2].expr}
			yyVAL.expr.SetPosition(yyDollar[2].expr.Position())
		}
	case 77:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:503
		{
			yyVAL.expr = &ast.UnaryExpr{Operator: "!", Expr: yyDollar[2].expr}
			yyVAL.expr.SetPosition(yyDollar[2].expr.Position())
		}
	case 78:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:508
		{
			yyVAL.expr = &ast.UnaryExpr{Operator: "^", Expr: yyDollar[2].expr}
			yyVAL.expr.SetPosition(yyDollar[2].expr.Position())
		}
	case 79:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:513
		{
			yyVAL.expr = &ast.AddrExpr{Expr: yyDollar[2].expr_ident}
			yyVAL.expr.SetPosition(yyDollar[2].expr_ident.Position())
		}
	case 80:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:518
		{
			yyVAL.expr = &ast.AddrExpr{Expr: &ast.MemberExpr{Expr: yyDollar[2].expr, Name: yyDollar[4].tok.Lit}}
			yyVAL.expr.SetPosition(yyDollar[2].expr.Position())
		}
	case 81:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:523
		{
			yyVAL.expr = &ast.DerefExpr{Expr: yyDollar[2].expr_ident}
			yyVAL.expr.SetPosition(yyDollar[2].expr_ident.Position())
		}
	case 82:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:528
		{
			yyVAL.expr = &ast.DerefExpr{Expr: &ast.MemberExpr{Expr: yyDollar[2].expr, Name: yyDollar[4].tok.Lit}}
			yyVAL.expr.SetPosition(yyDollar[2].expr.Position())
		}
	case 83:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:533
		{
			yyVAL.expr = &ast.StringExpr{Lit: yyDollar[1].tok.Lit}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 84:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:538
		{
			yyVAL.expr = &ast.ConstExpr{Value: yyDollar[1].tok.Lit}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:543
		{
			yyVAL.expr = &ast.ConstExpr{Value: yyDollar[1].tok.Lit}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 86:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:548
		{
			yyVAL.expr = &ast.ConstExpr{Value: yyDollar[1].tok.Lit}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 87:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:553
		{
			yyVAL.expr = &ast.TernaryOpExpr{Expr: yyDollar[1].expr, Lhs: yyDollar[3].expr, Rhs: yyDollar[5].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:558
		{
			yyVAL.expr = &ast.NilCoalescingOpExpr{Lhs: yyDollar[1].expr, Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:563
		{
			yyVAL.expr = &ast.MemberExpr{Expr: yyDollar[1].expr, Name: yyDollar[3].tok.Lit}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 90:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:568
		{
			yyVAL.expr = &ast.FuncExpr{Params: yyDollar[3].expr_idents, Stmts: yyDollar[6].compstmt}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 91:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:573
		{
			yyVAL.expr = &ast.FuncExpr{Params: yyDollar[3].expr_idents, Stmts: yyDollar[7].compstmt, VarArg: true}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 92:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:578
		{
			yyVAL.expr = &ast.FuncExpr{Name: yyDollar[2].tok.Lit, Params: yyDollar[4].expr_idents, Stmts: yyDollar[7].compstmt}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 93:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser.go.y:583
		{
			yyVAL.expr = &ast.FuncExpr{Name: yyDollar[2].tok.Lit, Params: yyDollar[4].expr_idents, Stmts: yyDollar[8].compstmt, VarArg: true}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 94:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:588
		{
			yyVAL.expr = &ast.ArrayExpr{Exprs: yyDollar[3].exprs}
			if l, ok := yylex.(*Lexer); ok {
				yyVAL.expr.SetPosition(l.pos)
			}
		}
	case 95:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:593
		{
			yyVAL.expr = &ast.MapExpr{MapExpr: yyDollar[3].map_expr}
			if l, ok := yylex.(*Lexer); ok {
				yyVAL.expr.SetPosition(l.pos)
			}
		}
	case 96:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:598
		{
			yyVAL.expr = &ast.ParenExpr{SubExpr: yyDollar[2].expr}
			if l, ok := yylex.(*Lexer); ok {
				yyVAL.expr.SetPosition(l.pos)
			}
		}
	case 97:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:603
		{
			yyVAL.expr = &ast.BinOpExpr{Lhs: yyDollar[1].expr, Operator: "+", Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 98:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:608
		{
			yyVAL.expr = &ast.BinOpExpr{Lhs: yyDollar[1].expr, Operator: "-", Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 99:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:613
		{
			yyVAL.expr = &ast.BinOpExpr{Lhs: yyDollar[1].expr, Operator: "*", Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 100:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:618
		{
			yyVAL.expr = &ast.BinOpExpr{Lhs: yyDollar[1].expr, Operator: "/", Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 101:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:623
		{
			yyVAL.expr = &ast.BinOpExpr{Lhs: yyDollar[1].expr, Operator: "%", Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 102:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:628
		{
			yyVAL.expr = &ast.BinOpExpr{Lhs: yyDollar[1].expr, Operator: "**", Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 103:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:633
		{
			yyVAL.expr = &ast.BinOpExpr{Lhs: yyDollar[1].expr, Operator: "<<", Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 104:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:638
		{
			yyVAL.expr = &ast.BinOpExpr{Lhs: yyDollar[1].expr, Operator: ">>", Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 105:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:643
		{
			yyVAL.expr = &ast.BinOpExpr{Lhs: yyDollar[1].expr, Operator: "==", Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 106:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:648
		{
			yyVAL.expr = &ast.BinOpExpr{Lhs: yyDollar[1].expr, Operator: "!=", Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 107:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:653
		{
			yyVAL.expr = &ast.BinOpExpr{Lhs: yyDollar[1].expr, Operator: ">", Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 108:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:658
		{
			yyVAL.expr = &ast.BinOpExpr{Lhs: yyDollar[1].expr, Operator: ">=", Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 109:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:663
		{
			yyVAL.expr = &ast.BinOpExpr{Lhs: yyDollar[1].expr, Operator: "<", Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 110:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:668
		{
			yyVAL.expr = &ast.BinOpExpr{Lhs: yyDollar[1].expr, Operator: "<=", Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 111:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:673
		{
			yyVAL.expr = &ast.AssocExpr{Lhs: yyDollar[1].expr, Operator: "+=", Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 112:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:678
		{
			yyVAL.expr = &ast.AssocExpr{Lhs: yyDollar[1].expr, Operator: "-=", Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 113:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:683
		{
			yyVAL.expr = &ast.AssocExpr{Lhs: yyDollar[1].expr, Operator: "*=", Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 114:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:688
		{
			yyVAL.expr = &ast.AssocExpr{Lhs: yyDollar[1].expr, Operator: "/=", Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 115:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:693
		{
			yyVAL.expr = &ast.AssocExpr{Lhs: yyDollar[1].expr, Operator: "&=", Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 116:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:698
		{
			yyVAL.expr = &ast.AssocExpr{Lhs: yyDollar[1].expr, Operator: "|=", Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 117:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:703
		{
			yyVAL.expr = &ast.AssocExpr{Lhs: yyDollar[1].expr, Operator: "++"}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 118:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:708
		{
			yyVAL.expr = &ast.AssocExpr{Lhs: yyDollar[1].expr, Operator: "--"}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 119:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:713
		{
			yyVAL.expr = &ast.BinOpExpr{Lhs: yyDollar[1].expr, Operator: "|", Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 120:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:718
		{
			yyVAL.expr = &ast.BinOpExpr{Lhs: yyDollar[1].expr, Operator: "||", Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 121:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:723
		{
			yyVAL.expr = &ast.BinOpExpr{Lhs: yyDollar[1].expr, Operator: "&", Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 122:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:728
		{
			yyVAL.expr = &ast.BinOpExpr{Lhs: yyDollar[1].expr, Operator: "&&", Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 123:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:733
		{
			yyVAL.expr = &ast.CallExpr{Name: yyDollar[1].tok.Lit, SubExprs: yyDollar[3].exprs, VarArg: true}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 124:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:738
		{
			yyVAL.expr = &ast.CallExpr{Name: yyDollar[1].tok.Lit, SubExprs: yyDollar[3].exprs}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 125:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:743
		{
			yyVAL.expr = &ast.AnonCallExpr{Expr: yyDollar[1].expr, SubExprs: yyDollar[3].exprs, VarArg: true}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 126:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:748
		{
			yyVAL.expr = &ast.AnonCallExpr{Expr: yyDollar[1].expr, SubExprs: yyDollar[3].exprs}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 127:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:753
		{
			yyVAL.expr = &ast.ItemExpr{Value: yyDollar[1].expr_ident, Index: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr_ident.Position())
		}
	case 128:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:758
		{
			yyVAL.expr = &ast.ItemExpr{Value: yyDollar[1].expr, Index: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 129:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:763
		{
			yyVAL.expr = yyDollar[1].expr_slice
			yyVAL.expr.SetPosition(yyDollar[1].expr_slice.Position())
		}
	case 130:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:768
		{
			yyVAL.expr = &ast.LenExpr{Expr: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 131:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:773
		{
			yyVAL.expr = &ast.NewExpr{Type: yyDollar[3].expr_type}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 132:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:778
		{
			yyVAL.expr = &ast.MakeChanExpr{Type: yyDollar[4].expr_type, SizeExpr: nil}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 133:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:783
		{
			yyVAL.expr = &ast.MakeChanExpr{Type: yyDollar[4].expr_type, SizeExpr: yyDollar[6].expr}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 134:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:788
		{
			yyVAL.expr = &ast.MakeExpr{Dimensions: yyDollar[3].array_count.Count, Type: yyDollar[4].expr_type}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 135:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:793
		{
			yyVAL.expr = &ast.MakeExpr{Dimensions: yyDollar[3].array_count.Count, Type: yyDollar[4].expr_type, LenExpr: yyDollar[6].expr}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 136:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser.go.y:798
		{
			yyVAL.expr = &ast.MakeExpr{Dimensions: yyDollar[3].array_count.Count, Type: yyDollar[4].expr_type, LenExpr: yyDollar[6].expr, CapExpr: yyDollar[8].expr}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 137:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:803
		{
			yyVAL.expr = &ast.MakeTypeExpr{Name: yyDollar[4].tok.Lit, Type: yyDollar[6].expr}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 138:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:808
		{
			yyVAL.expr = &ast.ChanExpr{Lhs: yyDollar[1].expr, Rhs: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 139:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:813
		{
			yyVAL.expr = &ast.ChanExpr{Rhs: yyDollar[2].expr}
			yyVAL.expr.SetPosition(yyDollar[2].expr.Position())
		}
	case 140:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:818
		{
			yyVAL.expr = &ast.DeleteExpr{WhatExpr: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 141:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:823
		{
			yyVAL.expr = &ast.DeleteExpr{WhatExpr: yyDollar[3].expr, KeyExpr: yyDollar[5].expr}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 142:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:828
		{
			yyVAL.expr = &ast.IncludeExpr{ItemExpr: yyDollar[1].expr, ListExpr: &ast.SliceExpr{Value: yyDollar[3].expr, Begin: nil, End: nil}}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 143:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:835
		{
			yyVAL.expr_ident = &ast.IdentExpr{Lit: yyDollar[1].tok.Lit}
			yyVAL.expr_ident.SetPosition(yyDollar[1].tok.Position())
		}
	}
	goto yystack /* stack new state and value */
}
