// Code generated by goyacc -o parser.go parser.go.y. DO NOT EDIT.

//line parser.go.y:1

package parser

import __yyfmt__ "fmt"

//line parser.go.y:3

import (
	"github.com/mattn/anko/ast"
)

//line parser.go.y:47
type yySymType struct {
	yys int
	tok ast.Token

	compstmt            ast.Stmt
	stmts               ast.Stmt
	stmt                ast.Stmt
	stmt_var_or_lets    ast.Stmt
	stmt_var            ast.Stmt
	stmt_lets           ast.Stmt
	stmt_if             ast.Stmt
	stmt_for            ast.Stmt
	stmt_switch         ast.Stmt
	stmt_switch_cases   ast.Stmt
	stmt_switch_case    ast.Stmt
	stmt_switch_default ast.Stmt
	stmt_select         ast.Stmt
	stmt_select_cases   ast.Stmt
	stmt_select_case    ast.Stmt
	stmt_select_default ast.Stmt

	exprs                []ast.Expr
	expr                 ast.Expr
	expr_idents          []string
	type_data            *ast.TypeStruct
	slice_count          int
	expr_member_or_ident ast.Expr
	expr_member          *ast.MemberExpr
	expr_ident           *ast.IdentExpr
	expr_literals        ast.Expr
	expr_map             *ast.MapExpr
	expr_slice           ast.Expr
	expr_unary           ast.Expr
	expr_binary          ast.Expr
	expr_lets            ast.Expr

	op_binary     ast.Operator
	op_comparison ast.Operator
	op_add        ast.Operator
	op_multiply   ast.Operator
}

const IDENT = 57346
const NUMBER = 57347
const STRING = 57348
const ARRAY = 57349
const VARARG = 57350
const FUNC = 57351
const RETURN = 57352
const VAR = 57353
const THROW = 57354
const IF = 57355
const ELSE = 57356
const FOR = 57357
const IN = 57358
const EQEQ = 57359
const NEQ = 57360
const GE = 57361
const LE = 57362
const OROR = 57363
const ANDAND = 57364
const NEW = 57365
const TRUE = 57366
const FALSE = 57367
const NIL = 57368
const NILCOALESCE = 57369
const MODULE = 57370
const TRY = 57371
const CATCH = 57372
const FINALLY = 57373
const PLUSEQ = 57374
const MINUSEQ = 57375
const MULEQ = 57376
const DIVEQ = 57377
const ANDEQ = 57378
const OREQ = 57379
const BREAK = 57380
const CONTINUE = 57381
const PLUSPLUS = 57382
const MINUSMINUS = 57383
const SHIFTLEFT = 57384
const SHIFTRIGHT = 57385
const SWITCH = 57386
const SELECT = 57387
const CASE = 57388
const DEFAULT = 57389
const GO = 57390
const CHAN = 57391
const MAKE = 57392
const OPCHAN = 57393
const TYPE = 57394
const LEN = 57395
const DELETE = 57396
const CLOSE = 57397
const MAP = 57398
const UNARY = 57399

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"NUMBER",
	"STRING",
	"ARRAY",
	"VARARG",
	"FUNC",
	"RETURN",
	"VAR",
	"THROW",
	"IF",
	"ELSE",
	"FOR",
	"IN",
	"EQEQ",
	"NEQ",
	"GE",
	"LE",
	"OROR",
	"ANDAND",
	"NEW",
	"TRUE",
	"FALSE",
	"NIL",
	"NILCOALESCE",
	"MODULE",
	"TRY",
	"CATCH",
	"FINALLY",
	"PLUSEQ",
	"MINUSEQ",
	"MULEQ",
	"DIVEQ",
	"ANDEQ",
	"OREQ",
	"BREAK",
	"CONTINUE",
	"PLUSPLUS",
	"MINUSMINUS",
	"SHIFTLEFT",
	"SHIFTRIGHT",
	"SWITCH",
	"SELECT",
	"CASE",
	"DEFAULT",
	"GO",
	"CHAN",
	"MAKE",
	"OPCHAN",
	"TYPE",
	"LEN",
	"DELETE",
	"CLOSE",
	"MAP",
	"'='",
	"':'",
	"'?'",
	"'<'",
	"'>'",
	"'+'",
	"'-'",
	"'|'",
	"'^'",
	"'*'",
	"'/'",
	"'%'",
	"'&'",
	"UNARY",
	"'{'",
	"'}'",
	"'('",
	"')'",
	"','",
	"';'",
	"'['",
	"']'",
	"'.'",
	"'!'",
	"'\\n'",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.go.y:1103

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 2,
	57, 65,
	75, 65,
	76, 5,
	-2, 1,
	-1, 24,
	75, 66,
	-2, 27,
	-1, 28,
	16, 102,
	-2, 65,
	-1, 67,
	57, 65,
	75, 65,
	-2, 5,
	-1, 119,
	16, 103,
	75, 103,
	-2, 116,
	-1, 124,
	4, 111,
	49, 111,
	56, 111,
	-2, 77,
	-1, 260,
	58, 5,
	-2, 65,
	-1, 264,
	72, 183,
	78, 183,
	-2, 175,
	-1, 282,
	72, 183,
	-2, 175,
	-1, 286,
	1, 68,
	8, 68,
	46, 68,
	47, 68,
	57, 68,
	58, 68,
	72, 68,
	74, 68,
	75, 68,
	76, 68,
	78, 68,
	81, 68,
	-2, 114,
	-1, 290,
	1, 17,
	46, 17,
	47, 17,
	58, 17,
	72, 17,
	76, 17,
	81, 17,
	-2, 82,
	-1, 292,
	1, 19,
	46, 19,
	47, 19,
	58, 19,
	72, 19,
	76, 19,
	81, 19,
	-2, 84,
	-1, 321,
	46, 55,
	47, 55,
	72, 55,
	-2, 170,
	-1, 327,
	72, 181,
	78, 181,
	-2, 176,
	-1, 344,
	1, 16,
	46, 16,
	47, 16,
	58, 16,
	72, 16,
	76, 16,
	81, 16,
	-2, 81,
	-1, 345,
	1, 18,
	46, 18,
	47, 18,
	58, 18,
	72, 18,
	76, 18,
	81, 18,
	-2, 83,
}

const yyPrivate = 57344

const yyLast = 3727

var yyAct = [...]int{

	71, 265, 225, 24, 9, 142, 314, 315, 8, 35,
	257, 258, 38, 317, 316, 72, 260, 259, 76, 7,
	5, 115, 210, 328, 127, 8, 69, 282, 113, 116,
	120, 124, 264, 8, 8, 83, 381, 134, 8, 84,
	125, 87, 215, 140, 210, 130, 330, 210, 8, 50,
	1, 8, 276, 148, 280, 210, 209, 210, 136, 149,
	150, 151, 152, 70, 210, 86, 133, 213, 24, 277,
	278, 143, 153, 141, 210, 202, 146, 337, 158, 159,
	372, 162, 163, 164, 345, 166, 168, 169, 69, 88,
	89, 171, 172, 173, 174, 175, 176, 177, 178, 179,
	180, 181, 182, 183, 184, 185, 186, 187, 188, 189,
	190, 191, 192, 193, 326, 128, 291, 227, 201, 399,
	197, 344, 83, 289, 128, 155, 84, 204, 87, 331,
	324, 297, 145, 165, 207, 198, 146, 218, 220, 130,
	130, 123, 130, 226, 205, 206, 69, 270, 130, 130,
	146, 130, 229, 135, 211, 212, 156, 214, 139, 138,
	132, 237, 137, 221, 222, 195, 224, 131, 244, 132,
	78, 77, 223, 440, 439, 208, 131, 129, 436, 198,
	325, 198, 292, 146, 435, 217, 129, 434, 133, 290,
	146, 262, 404, 240, 431, 228, 430, 133, 247, 428,
	422, 251, 421, 254, 248, 230, 232, 233, 417, 255,
	122, 342, 238, 271, 146, 267, 69, 416, 415, 413,
	274, 405, 401, 130, 396, 207, 392, 281, 263, 390,
	285, 6, 389, 388, 385, 366, 293, 68, 269, 352,
	296, 339, 286, 305, 298, 245, 302, 295, 287, 246,
	249, 231, 160, 309, 311, 383, 433, 261, 198, 241,
	146, 24, 318, 371, 370, 322, 126, 320, 319, 323,
	229, 154, 86, 121, 332, 74, 126, 284, 343, 336,
	368, 363, 321, 429, 341, 288, 69, 10, 340, 79,
	130, 317, 316, 260, 259, 304, 88, 89, 99, 100,
	279, 306, 350, 268, 144, 338, 170, 73, 4, 62,
	161, 2, 67, 359, 63, 66, 118, 329, 364, 360,
	362, 361, 96, 97, 98, 101, 64, 65, 48, 83,
	47, 373, 46, 84, 45, 87, 377, 32, 380, 51,
	130, 382, 31, 256, 23, 347, 196, 69, 313, 22,
	386, 21, 20, 126, 351, 374, 26, 25, 353, 354,
	3, 356, 0, 0, 0, 0, 0, 365, 0, 0,
	0, 0, 367, 0, 369, 0, 0, 406, 126, 0,
	408, 0, 0, 0, 0, 0, 0, 410, 0, 0,
	0, 0, 0, 0, 384, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 391, 0, 393, 394,
	0, 226, 427, 426, 397, 0, 0, 0, 0, 400,
	0, 402, 403, 0, 0, 0, 0, 0, 432, 0,
	126, 0, 0, 0, 412, 126, 0, 0, 0, 0,
	266, 126, 0, 0, 0, 0, 418, 0, 0, 419,
	420, 0, 0, 0, 0, 423, 0, 266, 0, 37,
	53, 54, 0, 0, 33, 13, 49, 14, 27, 0,
	28, 0, 0, 0, 0, 0, 0, 0, 40, 55,
	56, 57, 196, 15, 16, 437, 0, 438, 126, 0,
	0, 0, 0, 11, 12, 0, 327, 0, 0, 29,
	30, 0, 0, 17, 0, 41, 42, 0, 39, 18,
	19, 43, 0, 0, 327, 0, 0, 0, 52, 0,
	59, 61, 0, 0, 60, 0, 44, 0, 36, 0,
	0, 0, 34, 0, 0, 58, 0, 0, 0, 0,
	196, 0, 196, 0, 0, 126, 0, 0, 86, 105,
	106, 110, 108, 112, 111, 0, 0, 0, 0, 82,
	0, 266, 0, 0, 90, 91, 93, 94, 95, 92,
	0, 0, 88, 89, 99, 100, 0, 0, 0, 0,
	0, 0, 0, 85, 0, 0, 0, 0, 0, 0,
	196, 81, 107, 109, 102, 103, 104, 0, 96, 97,
	98, 101, 0, 0, 0, 83, 378, 379, 0, 84,
	0, 87, 0, 126, 0, 0, 0, 86, 105, 106,
	110, 108, 112, 111, 0, 0, 0, 0, 82, 0,
	0, 0, 0, 90, 91, 93, 94, 95, 92, 0,
	0, 88, 89, 99, 100, 0, 0, 0, 0, 0,
	0, 0, 85, 0, 0, 0, 0, 0, 266, 376,
	81, 107, 109, 102, 103, 104, 0, 96, 97, 98,
	101, 0, 0, 0, 83, 0, 0, 0, 84, 375,
	87, 86, 105, 106, 110, 108, 112, 111, 0, 0,
	0, 0, 82, 0, 0, 0, 0, 90, 91, 93,
	94, 95, 92, 0, 0, 88, 89, 99, 100, 0,
	0, 0, 0, 0, 0, 0, 85, 0, 0, 0,
	0, 0, 0, 349, 81, 107, 109, 102, 103, 104,
	0, 96, 97, 98, 101, 0, 0, 0, 83, 0,
	0, 0, 84, 348, 87, 86, 105, 106, 110, 108,
	112, 111, 0, 0, 0, 0, 82, 0, 0, 0,
	0, 90, 91, 93, 94, 95, 92, 0, 0, 88,
	89, 99, 100, 0, 0, 0, 0, 0, 0, 0,
	85, 0, 0, 0, 0, 0, 0, 335, 81, 107,
	109, 102, 103, 104, 0, 96, 97, 98, 101, 0,
	0, 0, 83, 0, 0, 0, 84, 334, 87, 86,
	105, 106, 110, 108, 112, 111, 0, 0, 0, 0,
	82, 0, 0, 0, 0, 90, 91, 93, 94, 95,
	92, 0, 0, 88, 89, 99, 100, 0, 0, 0,
	0, 0, 0, 0, 85, 0, 0, 0, 0, 0,
	0, 301, 81, 107, 109, 102, 103, 104, 0, 96,
	97, 98, 101, 0, 0, 0, 83, 0, 0, 0,
	84, 300, 87, 86, 105, 106, 110, 108, 112, 111,
	0, 0, 0, 0, 82, 0, 0, 0, 0, 90,
	91, 93, 94, 95, 92, 0, 0, 88, 89, 99,
	100, 0, 0, 0, 0, 0, 0, 0, 85, 0,
	0, 0, 0, 0, 0, 273, 81, 107, 109, 102,
	103, 104, 0, 96, 97, 98, 101, 0, 0, 0,
	83, 0, 0, 0, 84, 272, 87, 86, 105, 106,
	110, 108, 112, 111, 0, 0, 0, 0, 82, 0,
	0, 0, 0, 90, 91, 93, 94, 95, 92, 0,
	0, 88, 89, 99, 100, 0, 0, 0, 0, 0,
	0, 0, 85, 0, 0, 0, 0, 0, 0, 243,
	81, 107, 109, 102, 103, 104, 0, 96, 97, 98,
	101, 0, 0, 0, 83, 0, 0, 0, 84, 242,
	87, 86, 105, 106, 110, 108, 112, 111, 0, 0,
	0, 0, 82, 0, 0, 0, 0, 90, 91, 93,
	94, 95, 92, 0, 0, 88, 89, 99, 100, 0,
	0, 0, 0, 0, 0, 0, 85, 0, 0, 0,
	0, 0, 0, 0, 81, 107, 109, 102, 103, 104,
	0, 96, 97, 98, 101, 0, 0, 0, 83, 234,
	235, 0, 84, 0, 87, 86, 105, 106, 110, 108,
	112, 111, 0, 0, 0, 0, 82, 0, 0, 0,
	0, 90, 91, 93, 94, 95, 92, 0, 0, 88,
	89, 99, 100, 0, 0, 0, 0, 0, 0, 0,
	85, 0, 0, 0, 0, 0, 80, 0, 81, 107,
	109, 102, 103, 104, 0, 96, 97, 98, 101, 0,
	199, 0, 83, 0, 0, 0, 84, 0, 87, 86,
	105, 106, 110, 108, 112, 111, 0, 0, 0, 0,
	82, 0, 0, 0, 0, 90, 91, 93, 94, 95,
	92, 0, 0, 88, 89, 99, 100, 0, 0, 0,
	0, 0, 0, 0, 85, 0, 0, 0, 0, 0,
	0, 0, 81, 107, 109, 102, 103, 104, 0, 96,
	97, 98, 101, 0, 0, 0, 83, 425, 0, 0,
	84, 0, 87, 86, 105, 106, 110, 108, 112, 111,
	0, 0, 0, 0, 82, 0, 0, 0, 0, 90,
	91, 93, 94, 95, 92, 0, 0, 88, 89, 99,
	100, 0, 0, 0, 0, 0, 0, 0, 85, 0,
	0, 0, 0, 0, 0, 0, 81, 107, 109, 102,
	103, 104, 0, 96, 97, 98, 101, 0, 0, 0,
	83, 0, 0, 0, 84, 424, 87, 86, 105, 106,
	110, 108, 112, 111, 0, 0, 0, 0, 82, 0,
	0, 0, 0, 90, 91, 93, 94, 95, 92, 0,
	0, 88, 89, 99, 100, 0, 0, 0, 0, 0,
	0, 0, 85, 0, 0, 0, 0, 0, 0, 0,
	81, 107, 109, 102, 103, 104, 0, 96, 97, 98,
	101, 0, 0, 0, 83, 0, 0, 0, 84, 414,
	87, 86, 105, 106, 110, 108, 112, 111, 0, 0,
	0, 0, 82, 0, 0, 0, 0, 90, 91, 93,
	94, 95, 92, 0, 0, 88, 89, 99, 100, 0,
	0, 0, 0, 0, 0, 0, 85, 0, 0, 0,
	0, 0, 0, 411, 81, 107, 109, 102, 103, 104,
	0, 96, 97, 98, 101, 0, 0, 0, 83, 0,
	0, 0, 84, 0, 87, 86, 105, 106, 110, 108,
	112, 111, 0, 0, 0, 0, 82, 0, 0, 0,
	0, 90, 91, 93, 94, 95, 92, 0, 0, 88,
	89, 99, 100, 0, 0, 0, 0, 0, 0, 0,
	85, 0, 0, 0, 0, 0, 0, 0, 81, 107,
	109, 102, 103, 104, 0, 96, 97, 98, 101, 0,
	0, 0, 83, 409, 0, 0, 84, 0, 87, 86,
	105, 106, 110, 108, 112, 111, 0, 0, 0, 0,
	82, 0, 0, 0, 0, 90, 91, 93, 94, 95,
	92, 0, 0, 88, 89, 99, 100, 0, 0, 0,
	0, 0, 0, 0, 85, 0, 0, 0, 0, 0,
	0, 0, 81, 107, 109, 102, 103, 104, 0, 96,
	97, 98, 101, 0, 0, 0, 83, 0, 0, 0,
	84, 407, 87, 86, 105, 106, 110, 108, 112, 111,
	0, 0, 0, 0, 82, 0, 0, 0, 0, 90,
	91, 93, 94, 95, 92, 0, 0, 88, 89, 99,
	100, 0, 0, 0, 0, 0, 0, 0, 85, 0,
	0, 0, 0, 0, 0, 398, 81, 107, 109, 102,
	103, 104, 0, 96, 97, 98, 101, 0, 0, 0,
	83, 0, 0, 0, 84, 0, 87, 86, 105, 106,
	110, 108, 112, 111, 0, 0, 0, 0, 82, 0,
	0, 0, 0, 90, 91, 93, 94, 95, 92, 0,
	0, 88, 89, 99, 100, 0, 0, 0, 0, 0,
	0, 0, 85, 0, 0, 0, 0, 0, 0, 0,
	81, 107, 109, 102, 103, 104, 0, 96, 97, 98,
	101, 0, 395, 0, 83, 0, 0, 0, 84, 0,
	87, 86, 105, 106, 110, 108, 112, 111, 0, 0,
	0, 0, 82, 0, 0, 0, 0, 90, 91, 93,
	94, 95, 92, 0, 0, 88, 89, 99, 100, 0,
	0, 0, 0, 0, 0, 0, 85, 0, 0, 0,
	0, 0, 0, 0, 81, 107, 109, 102, 103, 104,
	0, 96, 97, 98, 101, 0, 0, 0, 83, 0,
	0, 0, 84, 387, 87, 86, 105, 106, 110, 108,
	112, 111, 0, 0, 0, 0, 82, 0, 0, 0,
	0, 90, 91, 93, 94, 95, 92, 0, 0, 88,
	89, 99, 100, 0, 0, 0, 0, 0, 0, 0,
	85, 0, 0, 0, 0, 0, 0, 0, 81, 107,
	109, 102, 103, 104, 0, 96, 97, 98, 101, 0,
	357, 0, 83, 0, 0, 0, 84, 0, 87, 86,
	105, 106, 110, 108, 112, 111, 0, 0, 0, 0,
	82, 0, 0, 0, 0, 90, 91, 93, 94, 95,
	92, 0, 0, 88, 89, 99, 100, 0, 0, 0,
	0, 0, 0, 0, 85, 0, 0, 0, 0, 0,
	0, 0, 81, 107, 109, 102, 103, 104, 0, 96,
	97, 98, 101, 0, 355, 0, 83, 0, 0, 0,
	84, 0, 87, 86, 105, 106, 110, 108, 112, 111,
	0, 0, 0, 0, 82, 0, 0, 0, 0, 90,
	91, 93, 94, 95, 92, 0, 0, 88, 89, 99,
	100, 0, 0, 0, 0, 0, 0, 0, 85, 0,
	0, 0, 0, 0, 0, 0, 81, 107, 109, 102,
	103, 104, 0, 96, 97, 98, 101, 0, 0, 0,
	83, 346, 0, 0, 84, 0, 87, 86, 105, 106,
	110, 108, 112, 111, 0, 0, 0, 0, 82, 0,
	0, 0, 0, 90, 91, 93, 94, 95, 92, 0,
	0, 88, 89, 99, 100, 0, 0, 0, 0, 0,
	0, 0, 85, 0, 0, 0, 0, 0, 0, 0,
	81, 107, 109, 102, 103, 104, 0, 96, 97, 98,
	101, 0, 0, 0, 83, 0, 0, 312, 84, 0,
	87, 86, 105, 106, 110, 108, 112, 111, 0, 0,
	0, 0, 82, 0, 0, 0, 0, 90, 91, 93,
	94, 95, 92, 0, 0, 88, 89, 99, 100, 0,
	0, 0, 0, 0, 0, 0, 85, 0, 0, 0,
	0, 0, 0, 0, 81, 107, 109, 102, 103, 104,
	0, 96, 97, 98, 101, 0, 307, 0, 83, 0,
	0, 0, 84, 0, 87, 86, 105, 106, 110, 108,
	112, 111, 0, 0, 0, 0, 82, 0, 0, 0,
	0, 90, 91, 93, 94, 95, 92, 0, 0, 88,
	89, 99, 100, 0, 0, 0, 0, 0, 0, 0,
	85, 0, 0, 0, 0, 0, 0, 0, 81, 107,
	109, 102, 103, 104, 0, 96, 97, 98, 101, 0,
	303, 0, 83, 0, 0, 0, 84, 0, 87, 86,
	105, 106, 110, 108, 112, 111, 0, 0, 0, 0,
	82, 0, 0, 0, 0, 90, 91, 93, 94, 95,
	92, 0, 0, 88, 89, 99, 100, 0, 0, 0,
	0, 0, 0, 0, 85, 0, 0, 0, 0, 0,
	0, 0, 81, 107, 109, 102, 103, 104, 0, 96,
	97, 98, 101, 0, 294, 0, 83, 0, 0, 0,
	84, 0, 87, 86, 105, 106, 110, 108, 112, 111,
	0, 0, 0, 0, 82, 0, 0, 0, 0, 90,
	91, 93, 94, 95, 92, 0, 0, 88, 89, 99,
	100, 0, 0, 0, 0, 0, 0, 0, 85, 0,
	0, 0, 0, 0, 0, 283, 81, 107, 109, 102,
	103, 104, 0, 96, 97, 98, 101, 0, 0, 0,
	83, 0, 0, 0, 84, 0, 87, 86, 105, 106,
	110, 108, 112, 111, 0, 0, 0, 0, 82, 0,
	0, 0, 0, 90, 91, 93, 94, 95, 92, 0,
	0, 88, 89, 99, 100, 0, 0, 0, 0, 0,
	0, 0, 85, 0, 0, 0, 0, 0, 0, 0,
	81, 107, 109, 102, 103, 104, 0, 96, 97, 98,
	101, 0, 0, 0, 83, 275, 0, 0, 84, 0,
	87, 86, 105, 106, 110, 108, 112, 111, 0, 0,
	0, 0, 82, 0, 0, 0, 0, 90, 91, 93,
	94, 95, 92, 0, 0, 88, 89, 99, 100, 0,
	0, 0, 0, 0, 0, 0, 85, 0, 0, 0,
	0, 0, 0, 0, 81, 107, 109, 102, 103, 104,
	0, 96, 97, 98, 101, 0, 0, 0, 83, 0,
	0, 252, 84, 0, 87, 86, 105, 106, 110, 108,
	112, 111, 0, 0, 0, 0, 82, 0, 0, 0,
	0, 90, 91, 93, 94, 95, 92, 0, 0, 88,
	89, 99, 100, 0, 0, 0, 0, 0, 0, 0,
	85, 0, 0, 0, 0, 0, 0, 239, 81, 107,
	109, 102, 103, 104, 0, 96, 97, 98, 101, 0,
	0, 0, 83, 0, 0, 0, 84, 0, 87, 86,
	105, 106, 110, 108, 112, 111, 0, 0, 0, 0,
	82, 0, 0, 0, 0, 90, 91, 93, 94, 95,
	92, 0, 0, 88, 89, 99, 100, 0, 0, 0,
	0, 0, 0, 0, 85, 0, 0, 0, 0, 0,
	0, 0, 81, 107, 109, 102, 103, 104, 0, 96,
	97, 98, 101, 0, 0, 0, 83, 236, 0, 0,
	84, 0, 87, 86, 105, 106, 110, 108, 112, 111,
	0, 0, 0, 0, 82, 0, 0, 0, 0, 90,
	91, 93, 94, 95, 92, 0, 0, 88, 89, 99,
	100, 0, 0, 0, 0, 0, 0, 0, 85, 0,
	0, 0, 0, 0, 0, 0, 81, 107, 109, 102,
	103, 104, 0, 96, 97, 98, 101, 0, 0, 0,
	83, 216, 0, 0, 84, 0, 87, 86, 105, 106,
	110, 108, 112, 111, 0, 0, 0, 0, 82, 0,
	0, 0, 0, 90, 91, 93, 94, 95, 92, 0,
	0, 88, 89, 99, 100, 0, 0, 0, 0, 0,
	0, 0, 85, 0, 0, 0, 0, 0, 0, 0,
	81, 107, 109, 102, 103, 104, 0, 96, 97, 98,
	101, 0, 203, 0, 83, 0, 0, 0, 84, 0,
	87, 86, 105, 106, 110, 108, 112, 111, 0, 0,
	0, 0, 82, 0, 0, 0, 0, 90, 91, 93,
	94, 95, 92, 0, 0, 88, 89, 99, 100, 0,
	0, 0, 0, 0, 0, 0, 85, 0, 0, 0,
	0, 0, 0, 0, 81, 107, 109, 102, 103, 104,
	0, 96, 97, 98, 101, 0, 194, 0, 83, 0,
	0, 0, 84, 0, 87, 86, 105, 106, 110, 108,
	112, 111, 0, 0, 0, 0, 82, 0, 0, 0,
	0, 90, 91, 93, 94, 95, 92, 0, 0, 88,
	89, 99, 100, 0, 0, 0, 0, 0, 0, 0,
	85, 0, 0, 0, 0, 0, 80, 0, 81, 107,
	109, 102, 103, 104, 0, 96, 97, 98, 101, 0,
	0, 0, 83, 0, 0, 0, 84, 0, 87, 86,
	105, 106, 110, 108, 112, 111, 0, 0, 0, 0,
	82, 0, 0, 0, 0, 90, 91, 93, 94, 95,
	92, 0, 0, 88, 89, 99, 100, 0, 0, 0,
	0, 0, 0, 0, 85, 0, 0, 0, 0, 0,
	0, 0, 81, 107, 109, 102, 103, 104, 0, 96,
	97, 98, 101, 0, 0, 0, 83, 0, 0, 0,
	84, 0, 87, 86, 105, 106, 110, 108, 112, 111,
	0, 0, 0, 0, 82, 0, 0, 0, 0, 90,
	91, 93, 94, 95, 92, 0, 0, 88, 89, 99,
	100, 0, 0, 0, 0, 0, 0, 0, 85, 0,
	0, 0, 0, 0, 0, 0, 81, 107, 109, 102,
	103, 104, 0, 96, 97, 98, 101, 0, 0, 0,
	157, 0, 0, 0, 84, 0, 87, 86, 105, 106,
	110, 108, 112, 111, 0, 0, 0, 0, 82, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 88, 89, 99, 100, 0, 0, 0, 0, 0,
	0, 0, 85, 0, 0, 0, 0, 0, 0, 0,
	81, 107, 109, 102, 103, 104, 0, 96, 97, 98,
	101, 0, 0, 0, 83, 0, 0, 0, 84, 0,
	87, 86, 105, 106, 110, 108, 112, 111, 0, 0,
	0, 0, 82, 0, 119, 53, 54, 0, 0, 33,
	0, 49, 0, 0, 0, 88, 89, 99, 100, 0,
	0, 0, 0, 40, 55, 56, 57, 0, 0, 0,
	0, 0, 0, 0, 81, 107, 109, 102, 103, 104,
	0, 96, 97, 98, 101, 0, 0, 0, 83, 0,
	41, 42, 84, 39, 87, 0, 43, 0, 0, 0,
	0, 0, 0, 52, 0, 59, 61, 0, 0, 60,
	0, 114, 0, 36, 0, 0, 117, 34, 0, 0,
	58, 37, 53, 54, 0, 0, 33, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	40, 55, 56, 57, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 37, 53, 54, 0, 0,
	33, 0, 0, 0, 0, 0, 0, 41, 42, 0,
	39, 0, 0, 43, 40, 55, 56, 57, 0, 0,
	52, 0, 59, 61, 0, 0, 60, 0, 44, 0,
	36, 37, 53, 54, 34, 333, 33, 58, 0, 0,
	0, 41, 42, 0, 39, 0, 0, 43, 0, 0,
	40, 55, 56, 57, 52, 0, 59, 61, 0, 0,
	60, 0, 44, 0, 36, 0, 0, 0, 34, 299,
	0, 58, 0, 0, 0, 0, 0, 41, 42, 0,
	39, 0, 0, 43, 0, 86, 105, 106, 110, 108,
	52, 111, 59, 61, 0, 0, 60, 0, 44, 0,
	36, 0, 0, 253, 34, 0, 0, 58, 0, 88,
	89, 99, 100, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 107,
	109, 102, 103, 104, 0, 96, 97, 98, 101, 37,
	53, 54, 83, 0, 33, 0, 84, 0, 87, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 40, 55,
	56, 57, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 37, 53, 54, 0, 0,
	33, 0, 0, 0, 0, 41, 42, 0, 39, 0,
	0, 43, 0, 219, 40, 55, 56, 57, 52, 0,
	59, 61, 0, 0, 60, 0, 44, 0, 36, 37,
	53, 54, 34, 0, 33, 58, 0, 0, 0, 0,
	0, 41, 42, 0, 39, 0, 0, 43, 40, 55,
	56, 57, 0, 0, 52, 0, 59, 61, 0, 0,
	60, 0, 44, 0, 36, 0, 0, 200, 34, 0,
	0, 58, 0, 0, 0, 41, 42, 0, 39, 0,
	0, 43, 0, 167, 0, 0, 0, 0, 52, 0,
	59, 61, 0, 0, 60, 0, 44, 0, 36, 37,
	53, 54, 34, 0, 33, 58, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 40, 55,
	56, 57, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 37, 53, 54, 0, 0, 33, 0,
	0, 0, 0, 0, 0, 41, 42, 0, 39, 0,
	0, 43, 40, 55, 56, 57, 0, 0, 52, 0,
	59, 61, 0, 0, 60, 0, 44, 0, 36, 37,
	53, 54, 34, 0, 33, 58, 0, 0, 0, 41,
	42, 0, 39, 0, 0, 43, 0, 0, 40, 55,
	56, 57, 52, 0, 59, 61, 0, 0, 60, 0,
	358, 0, 36, 37, 53, 54, 34, 0, 33, 58,
	0, 0, 0, 0, 0, 41, 42, 0, 39, 0,
	0, 43, 40, 55, 56, 57, 0, 0, 52, 0,
	59, 61, 0, 0, 60, 0, 310, 0, 36, 37,
	53, 54, 34, 0, 33, 58, 0, 0, 0, 41,
	42, 0, 39, 0, 0, 43, 0, 0, 40, 55,
	56, 57, 52, 0, 59, 61, 0, 0, 60, 0,
	308, 0, 36, 0, 0, 0, 34, 0, 0, 58,
	0, 0, 0, 0, 0, 41, 42, 0, 39, 0,
	0, 43, 86, 105, 106, 110, 108, 0, 52, 0,
	59, 61, 0, 0, 60, 0, 250, 0, 36, 0,
	0, 0, 34, 0, 0, 58, 88, 89, 99, 100,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 107, 109, 102, 103,
	104, 0, 96, 97, 98, 101, 37, 147, 54, 83,
	0, 33, 0, 84, 0, 87, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 40, 55, 56, 57, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	75, 53, 54, 0, 0, 33, 0, 0, 0, 0,
	0, 0, 41, 42, 0, 39, 0, 0, 43, 40,
	55, 56, 57, 0, 0, 52, 0, 59, 61, 0,
	0, 60, 0, 44, 0, 36, 0, 0, 0, 34,
	0, 0, 58, 0, 0, 0, 41, 42, 0, 39,
	0, 0, 43, 86, 0, 0, 0, 0, 0, 52,
	0, 59, 61, 0, 0, 60, 0, 44, 0, 36,
	0, 0, 0, 34, 0, 0, 58, 88, 89, 99,
	100, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 102,
	103, 104, 0, 96, 97, 98, 101, 0, 0, 0,
	83, 0, 0, 0, 84, 0, 87,
}
var yyPact = [...]int{

	-56, -1000, 455, -56, -1000, -73, -73, -1000, -1000, -1000,
	-1000, -1000, -1000, 3325, 3325, 303, 204, 3606, 98, 97,
	275, -1000, -1000, -1000, 2649, -1000, -1000, 3325, 2930, 3325,
	202, -1000, -1000, 137, -47, 111, 3325, 80, -19, 89,
	86, 85, 3325, -4, -73, -1000, -1000, -1000, -1000, 300,
	75, -1000, 3572, -1000, -1000, -1000, -1000, -1000, 3325, 3325,
	3325, 3325, -1000, -1000, -1000, -1000, -1000, 455, -73, -1000,
	1, 2713, 2713, 200, -56, 83, 2777, 3325, 3325, 239,
	3325, 3325, 3325, 3325, 3255, 3325, 3325, 302, -1000, -1000,
	3325, 3325, 3325, 3325, 3325, 3325, 3325, 3325, 3325, 3325,
	3325, 3325, 3325, 3325, 3325, 3325, 3325, 3325, 3325, 3325,
	3325, 3325, 3325, 2585, -56, 104, 1049, 3221, -1, 80,
	2521, -73, 300, 72, -11, 3325, -73, -15, -1000, 111,
	111, -10, 111, -36, 2457, 3325, 3185, 3325, 111, 120,
	2841, 111, 3325, 60, -1000, 3325, -73, -1000, -38, -38,
	-38, -38, -38, -1000, -56, 179, 3325, 3325, 985, 2393,
	3325, -56, 2713, 2329, 2905, 185, 921, 3325, 2841, 49,
	-1000, 2713, 2713, 2713, 2713, 2713, 2713, 49, 49, 49,
	49, 49, 49, 256, 256, 256, 3647, 3647, 3647, 3647,
	3647, 3647, 3506, 3119, -56, 177, -73, 3325, -73, -56,
	3465, 2265, 3077, -73, 247, 183, 300, -1000, -43, -73,
	299, -57, -57, 111, -57, -11, -1000, 139, 857, 3325,
	2201, -22, -5, 296, -24, -48, 2137, 3325, 1, 3325,
	176, 255, 115, 108, -1000, 3325, -1000, 2073, 175, 3325,
	57, -1000, -1000, 3041, 793, 174, -1000, 2009, 291, 171,
	-56, 1945, 3429, 3395, 1881, 245, -30, -1000, -1000, 224,
	455, 198, 56, 106, -73, -55, -73, 3325, -1000, -32,
	55, -1000, -1000, 3007, 729, -1000, -1000, -1000, 3325, 2,
	111, 169, -73, 3325, 1, 2713, -19, -1000, 207, 47,
	-1000, 10, -1000, 1817, -56, -1000, 2841, -1000, 665, -1000,
	-1000, 3325, -1000, -56, -1000, -1000, 167, -56, -56, 1753,
	-56, 1689, 3359, -33, -1000, -1000, 223, 3325, 163, -1000,
	-1000, -56, 222, -56, 193, 192, 6, -73, -1000, -43,
	111, -1000, 601, -1000, -1000, 3325, 532, 3325, -35, -1000,
	3325, 2713, 184, -56, -1000, -1000, -1000, 162, -1000, 3325,
	1625, 161, -1000, 160, 157, -56, 154, -56, -56, 1561,
	152, -1000, -1000, -56, 1497, 61, -1000, -1000, -56, 150,
	-56, -56, 121, 149, -57, -1000, 3325, 1433, -1000, 3325,
	1369, -73, 1305, -56, 147, -1000, 1241, -1000, -1000, -1000,
	-1000, 146, -1000, 145, 136, -56, -1000, -1000, -56, -56,
	-1000, -1000, 130, 128, -56, -1000, 1177, -1000, 1113, -1000,
	3325, 3325, 127, 252, -1000, -1000, -1000, -1000, 124, -1000,
	-1000, -1000, -1000, 122, -1000, -1000, -48, 2713, 225, 116,
	-1000, -1000, 112, 107, -56, -1000, -56, 102, 101, -1000,
	-1000,
}
var yyPgo = [...]int{

	0, 50, 360, 4, 287, 357, 356, 352, 351, 349,
	348, 7, 6, 344, 343, 11, 10, 49, 0, 21,
	24, 9, 342, 339, 12, 337, 2, 334, 332, 330,
	328, 327, 326, 314, 309, 311, 308, 5, 1, 231,
	19,
}
var yyR1 = [...]int{

	0, 1, 1, 2, 2, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 4, 4,
	5, 6, 6, 7, 7, 7, 8, 8, 8, 8,
	8, 8, 8, 8, 8, 8, 8, 13, 14, 14,
	14, 14, 14, 15, 16, 16, 9, 10, 10, 10,
	10, 10, 11, 11, 12, 17, 17, 17, 17, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 18, 19, 19, 19, 20, 20, 20, 20, 20,
	20, 21, 21, 22, 22, 23, 24, 25, 25, 25,
	25, 25, 25, 26, 26, 26, 27, 27, 27, 27,
	27, 27, 27, 27, 27, 27, 28, 28, 28, 28,
	28, 29, 29, 29, 29, 30, 30, 30, 30, 30,
	30, 30, 30, 34, 34, 34, 34, 34, 34, 33,
	33, 33, 32, 32, 32, 32, 32, 32, 31, 31,
	35, 35, 36, 36, 36, 37, 37, 39, 39, 40,
	38, 38, 38, 38,
}
var yyR2 = [...]int{

	0, 1, 2, 2, 3, 0, 1, 1, 1, 2,
	2, 5, 13, 12, 9, 8, 6, 5, 6, 5,
	4, 6, 4, 1, 1, 1, 1, 1, 1, 1,
	4, 3, 3, 5, 7, 5, 4, 7, 5, 6,
	7, 7, 8, 7, 8, 8, 9, 6, 0, 1,
	1, 2, 2, 4, 3, 2, 7, 0, 1, 1,
	2, 2, 4, 4, 3, 0, 1, 4, 4, 1,
	1, 5, 3, 7, 8, 8, 9, 2, 5, 7,
	3, 5, 4, 5, 4, 4, 4, 4, 4, 4,
	6, 8, 7, 3, 2, 3, 10, 5, 1, 1,
	1, 1, 0, 1, 4, 1, 3, 2, 2, 5,
	2, 2, 3, 1, 1, 3, 1, 2, 1, 1,
	1, 1, 1, 0, 3, 6, 6, 5, 5, 7,
	8, 6, 5, 5, 7, 8, 2, 2, 2, 2,
	2, 1, 1, 1, 1, 2, 2, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	0, 1, 2, 1, 1, 0, 1, 1, 2, 1,
	0, 2, 1, 1,
}
var yyChk = [...]int{

	-1000, -1, -35, -2, -36, 76, -39, -40, 81, -3,
	-4, 38, 39, 10, 12, 28, 29, 48, 54, 55,
	-7, -8, -9, -13, -18, -5, -6, 13, 15, 44,
	45, -22, -25, 9, 77, -21, 73, 4, -24, 53,
	23, 50, 51, 56, 71, -27, -28, -29, -30, 11,
	-17, -23, 63, 5, 6, 24, 25, 26, 80, 65,
	69, 66, -34, -33, -32, -31, -35, -36, -39, -40,
	-17, -18, -18, 4, 71, 4, -18, 73, 73, 14,
	57, 59, 27, 73, 77, 51, 16, 79, 40, 41,
	32, 33, 37, 34, 35, 36, 66, 67, 68, 42,
	43, 69, 62, 63, 64, 17, 18, 60, 20, 61,
	19, 22, 21, -18, 71, -19, -18, 76, -4, 4,
	-18, 71, 73, 4, 78, -37, -39, -20, 4, 66,
	-21, 56, 49, 77, -18, 73, 77, 73, 73, 73,
	-18, 77, -37, -19, 4, 57, 75, 5, -18, -18,
	-18, -18, -18, -3, 71, -1, 73, 73, -18, -18,
	13, 71, -18, -18, -18, -17, -18, 58, -18, -18,
	4, -18, -18, -18, -18, -18, -18, -18, -18, -18,
	-18, -18, -18, -18, -18, -18, -18, -18, -18, -18,
	-18, -18, -18, -18, 71, -1, -39, 16, 75, 71,
	76, -18, 76, 71, -37, -19, 73, -21, -17, 71,
	79, -20, -20, 77, -20, 78, 74, -17, -18, 58,
	-18, -20, -20, 52, -20, -26, -18, 57, -17, -37,
	-1, 72, -17, -17, 74, 75, 74, -18, -1, 58,
	8, 74, 78, 58, -18, -1, 72, -18, -37, -1,
	71, -18, 76, 76, -18, -37, -14, -16, -15, 47,
	46, 74, 8, -19, 75, -38, -39, -37, 4, -20,
	8, 74, 78, 58, -18, 74, 74, 74, 75, 4,
	78, -38, 75, 58, -17, -18, -24, 72, 30, 8,
	74, 8, 74, -18, 71, 72, -18, 74, -18, 78,
	78, 58, 72, 71, 4, 72, -1, 71, 71, -18,
	71, -18, 76, -10, -12, -11, 47, 46, -37, -15,
	-16, 58, -3, 71, 74, 74, 8, -39, 78, -17,
	78, 74, -18, 78, 78, 58, -18, 75, -20, 72,
	-37, -18, 4, 71, 74, 74, 74, -1, 78, 58,
	-18, -1, 72, -1, -1, 71, -1, 71, 71, -18,
	-37, -11, -12, 58, -18, -17, 72, -1, 58, -1,
	71, 71, 74, -38, -20, 78, 58, -18, 74, 75,
	-18, 71, -18, 71, -1, 72, -18, 78, 72, 72,
	72, -1, 72, -1, -1, 71, 72, -1, 58, 58,
	-1, 72, -1, -1, 71, 72, -18, 78, -18, 74,
	-37, 58, -1, 72, 78, 72, 72, 72, -1, -1,
	-1, 72, 72, -1, 78, 74, -26, -18, 72, 31,
	72, 72, -38, 31, 71, 72, 71, -1, -1, 72,
	72,
}
var yyDef = [...]int{

	170, -2, -2, 170, 171, 174, 173, 177, 179, 3,
	6, 7, 8, 65, 0, 0, 0, 0, 0, 0,
	23, 24, 25, 26, -2, 28, 29, 0, -2, 0,
	0, 69, 70, 0, 175, 0, 0, 116, 114, 0,
	0, 0, 0, 0, 175, 98, 99, 100, 101, 102,
	0, 113, 0, 118, 119, 120, 121, 122, 0, 0,
	0, 0, 141, 142, 143, 144, 2, -2, 172, 178,
	9, 66, 10, 0, 170, 116, 0, 0, 0, 0,
	0, 0, 0, 65, 0, 0, 0, 0, 145, 146,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 170, 0, 66, 0, 0, -2,
	0, 175, 102, 0, -2, 65, 176, 0, 105, 0,
	0, 0, 0, 0, 0, 65, 0, 0, 0, 0,
	94, 0, 123, 0, 103, 65, 175, 117, 136, 137,
	138, 139, 140, 4, 170, 0, 65, 65, 0, 0,
	0, 170, 31, 0, 72, 0, 0, 0, 93, 95,
	115, 147, 148, 149, 150, 151, 152, 153, 154, 155,
	156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
	166, 167, 168, 169, 170, 0, 173, 0, 175, 170,
	0, 0, 0, 175, 48, 0, 102, 112, 180, 175,
	0, 107, 108, 0, 110, 111, 80, 0, 0, 0,
	0, 0, 0, 0, 0, 180, 0, 65, 32, 0,
	0, 0, 0, 0, 20, 0, 22, 0, 0, 0,
	0, 84, 86, 0, 0, 0, 36, 0, 0, 0,
	170, 0, 0, 0, 0, 57, 175, 49, 50, 0,
	-2, 0, 0, 0, -2, 0, 182, 65, 106, 0,
	0, 82, 85, 0, 0, 87, 88, 89, 0, 0,
	0, 0, -2, 0, 30, 67, -2, 11, 0, 0,
	-2, 0, -2, 0, 170, 35, 71, 83, 0, 132,
	133, 0, 33, 170, 104, 38, 0, 170, 170, 0,
	170, 0, 0, 175, 58, 59, 0, 65, 0, 51,
	52, -2, 0, 170, 0, 0, 0, -2, 78, 180,
	0, 81, 0, 127, 128, 0, 0, 0, 0, 97,
	0, 124, 0, 170, -2, -2, 21, 0, 131, 0,
	0, 0, 39, 0, 0, 170, 0, 170, 170, 0,
	0, 60, 61, 170, 66, 0, 47, 54, 170, 0,
	170, 170, 0, 0, 109, 126, 0, 0, 90, 0,
	0, 175, 0, 170, 0, 34, 0, 134, 37, 40,
	41, 0, 43, 0, 0, 170, 56, 64, 170, 170,
	53, 73, 0, 0, 170, 79, 0, 129, 0, 92,
	123, 0, 0, 15, 135, 42, 44, 45, 0, 62,
	63, 74, 75, 0, 130, 91, 180, 125, 14, 0,
	46, 76, 0, 0, 170, 96, 170, 0, 0, 13,
	12,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	81, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 80, 3, 3, 3, 68, 69, 3,
	73, 74, 66, 62, 75, 63, 79, 67, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 58, 76,
	60, 57, 61, 59, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 77, 3, 78, 65, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 71, 64, 72,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 70,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:112
		{
			yyVAL.compstmt = nil
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:116
		{
			yyVAL.compstmt = yyDollar[1].stmts
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:122
		{
			if yyDollar[2].stmt != nil {
				yyVAL.stmts = &ast.StmtsStmt{Stmts: []ast.Stmt{yyDollar[2].stmt}}
			}
			if l, ok := yylex.(*Lexer); ok {
				l.stmt = yyVAL.stmts
			}
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:131
		{
			if yyDollar[3].stmt != nil {
				if yyDollar[1].stmts == nil {
					yyVAL.stmts = &ast.StmtsStmt{Stmts: []ast.Stmt{yyDollar[3].stmt}}
				} else {
					stmts := yyDollar[1].stmts.(*ast.StmtsStmt)
					stmts.Stmts = append(stmts.Stmts, yyDollar[3].stmt)
				}
				if l, ok := yylex.(*Lexer); ok {
					l.stmt = yyVAL.stmts
				}
			}
		}
	case 5:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:147
		{
			yyVAL.stmt = nil
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:151
		{
			yyVAL.stmt = yyDollar[1].stmt_var_or_lets
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:155
		{
			yyVAL.stmt = &ast.BreakStmt{}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:160
		{
			yyVAL.stmt = &ast.ContinueStmt{}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:165
		{
			yyVAL.stmt = &ast.ReturnStmt{Exprs: yyDollar[2].exprs}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:170
		{
			yyVAL.stmt = &ast.ThrowStmt{Expr: yyDollar[2].expr}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 11:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:175
		{
			yyVAL.stmt = &ast.ModuleStmt{Name: yyDollar[2].tok.Lit, Stmt: yyDollar[4].compstmt}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 12:
		yyDollar = yyS[yypt-13 : yypt+1]
//line parser.go.y:180
		{
			yyVAL.stmt = &ast.TryStmt{Try: yyDollar[3].compstmt, Var: yyDollar[6].tok.Lit, Catch: yyDollar[8].compstmt, Finally: yyDollar[12].compstmt}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 13:
		yyDollar = yyS[yypt-12 : yypt+1]
//line parser.go.y:185
		{
			yyVAL.stmt = &ast.TryStmt{Try: yyDollar[3].compstmt, Catch: yyDollar[7].compstmt, Finally: yyDollar[11].compstmt}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 14:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser.go.y:190
		{
			yyVAL.stmt = &ast.TryStmt{Try: yyDollar[3].compstmt, Var: yyDollar[6].tok.Lit, Catch: yyDollar[8].compstmt}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 15:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:195
		{
			yyVAL.stmt = &ast.TryStmt{Try: yyDollar[3].compstmt, Catch: yyDollar[7].compstmt}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 16:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:200
		{
			yyVAL.stmt = &ast.GoroutineStmt{Expr: &ast.CallExpr{Name: yyDollar[2].tok.Lit, SubExprs: yyDollar[4].exprs, VarArg: true, Go: true}}
			yyVAL.stmt.SetPosition(yyDollar[2].tok.Position())
		}
	case 17:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:205
		{
			yyVAL.stmt = &ast.GoroutineStmt{Expr: &ast.CallExpr{Name: yyDollar[2].tok.Lit, SubExprs: yyDollar[4].exprs, Go: true}}
			yyVAL.stmt.SetPosition(yyDollar[2].tok.Position())
		}
	case 18:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:210
		{
			yyVAL.stmt = &ast.GoroutineStmt{Expr: &ast.AnonCallExpr{Expr: yyDollar[2].expr, SubExprs: yyDollar[4].exprs, VarArg: true, Go: true}}
			yyVAL.stmt.SetPosition(yyDollar[2].expr.Position())
		}
	case 19:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:215
		{
			yyVAL.stmt = &ast.GoroutineStmt{Expr: &ast.AnonCallExpr{Expr: yyDollar[2].expr, SubExprs: yyDollar[4].exprs, Go: true}}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 20:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:220
		{
			yyVAL.stmt = &ast.DeleteStmt{Item: yyDollar[3].expr}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 21:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:225
		{
			yyVAL.stmt = &ast.DeleteStmt{Item: yyDollar[3].expr, Key: yyDollar[5].expr}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 22:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:230
		{
			yyVAL.stmt = &ast.CloseStmt{Expr: yyDollar[3].expr}
			yyVAL.stmt.SetPosition(yyDollar[1].tok.Position())
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:235
		{
			yyVAL.stmt = yyDollar[1].stmt_if
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:239
		{
			yyVAL.stmt = yyDollar[1].stmt_for
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:243
		{
			yyVAL.stmt = yyDollar[1].stmt_switch
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:247
		{
			yyVAL.stmt = yyDollar[1].stmt_select
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:251
		{
			yyVAL.stmt = &ast.ExprStmt{Expr: yyDollar[1].expr}
			yyVAL.stmt.SetPosition(yyDollar[1].expr.Position())
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:258
		{
			yyVAL.stmt_var_or_lets = yyDollar[1].stmt_var
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:262
		{
			yyVAL.stmt_var_or_lets = yyDollar[1].stmt_lets
		}
	case 30:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:268
		{
			yyVAL.stmt_var = &ast.VarStmt{Names: yyDollar[2].expr_idents, Exprs: yyDollar[4].exprs}
			yyVAL.stmt_var.SetPosition(yyDollar[1].tok.Position())
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:275
		{
			yyVAL.stmt_lets = &ast.LetsStmt{LHSS: []ast.Expr{yyDollar[1].expr}, RHSS: []ast.Expr{yyDollar[3].expr}}
			yyVAL.stmt_lets.SetPosition(yyDollar[1].expr.Position())
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:280
		{
			if len(yyDollar[1].exprs) == 2 && len(yyDollar[3].exprs) == 1 {
				if _, ok := yyDollar[3].exprs[0].(*ast.ItemExpr); ok {
					yyVAL.stmt_lets = &ast.LetMapItemStmt{LHSS: yyDollar[1].exprs, RHS: yyDollar[3].exprs[0]}
				} else {
					yyVAL.stmt_lets = &ast.LetsStmt{LHSS: yyDollar[1].exprs, RHSS: yyDollar[3].exprs}
				}
			} else {
				yyVAL.stmt_lets = &ast.LetsStmt{LHSS: yyDollar[1].exprs, RHSS: yyDollar[3].exprs}
			}
		}
	case 33:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:294
		{
			yyVAL.stmt_if = &ast.IfStmt{If: yyDollar[2].expr, Then: yyDollar[4].compstmt, Else: nil}
			yyVAL.stmt_if.SetPosition(yyDollar[1].tok.Position())
		}
	case 34:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:299
		{
			ifStmt := yyDollar[1].stmt_if.(*ast.IfStmt)
			ifStmt.ElseIf = append(ifStmt.ElseIf, &ast.IfStmt{If: yyDollar[4].expr, Then: yyDollar[6].compstmt})
		}
	case 35:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:304
		{
			ifStmt := yyDollar[1].stmt_if.(*ast.IfStmt)
			if ifStmt.Else != nil {
				yylex.Error("multiple else statement")
			}
			ifStmt.Else = yyDollar[4].compstmt
		}
	case 36:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:314
		{
			yyVAL.stmt_for = &ast.LoopStmt{Stmt: yyDollar[3].compstmt}
			yyVAL.stmt_for.SetPosition(yyDollar[1].tok.Position())
		}
	case 37:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:319
		{
			if len(yyDollar[2].expr_idents) < 1 {
				yylex.Error("missing identifier")
			} else if len(yyDollar[2].expr_idents) > 2 {
				yylex.Error("too many identifiers")
			} else {
				yyVAL.stmt_for = &ast.ForStmt{Vars: yyDollar[2].expr_idents, Value: yyDollar[4].expr, Stmt: yyDollar[6].compstmt}
				yyVAL.stmt_for.SetPosition(yyDollar[1].tok.Position())
			}
		}
	case 38:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:330
		{
			yyVAL.stmt_for = &ast.LoopStmt{Expr: yyDollar[2].expr, Stmt: yyDollar[4].compstmt}
			yyVAL.stmt_for.SetPosition(yyDollar[1].tok.Position())
		}
	case 39:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:335
		{
			yyVAL.stmt_for = &ast.CForStmt{Stmt: yyDollar[5].compstmt}
			yyVAL.stmt_for.SetPosition(yyDollar[1].tok.Position())
		}
	case 40:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:340
		{
			yyVAL.stmt_for = &ast.CForStmt{Expr3: yyDollar[4].expr, Stmt: yyDollar[6].compstmt}
			yyVAL.stmt_for.SetPosition(yyDollar[1].tok.Position())
		}
	case 41:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:345
		{
			yyVAL.stmt_for = &ast.CForStmt{Expr2: yyDollar[3].expr, Stmt: yyDollar[6].compstmt}
			yyVAL.stmt_for.SetPosition(yyDollar[1].tok.Position())
		}
	case 42:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:350
		{
			yyVAL.stmt_for = &ast.CForStmt{Expr2: yyDollar[3].expr, Expr3: yyDollar[5].expr, Stmt: yyDollar[7].compstmt}
			yyVAL.stmt_for.SetPosition(yyDollar[1].tok.Position())
		}
	case 43:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:355
		{
			yyVAL.stmt_for = &ast.CForStmt{Stmt1: yyDollar[2].stmt_var_or_lets, Stmt: yyDollar[6].compstmt}
			yyVAL.stmt_for.SetPosition(yyDollar[1].tok.Position())
		}
	case 44:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:360
		{
			yyVAL.stmt_for = &ast.CForStmt{Stmt1: yyDollar[2].stmt_var_or_lets, Expr3: yyDollar[5].expr, Stmt: yyDollar[7].compstmt}
			yyVAL.stmt_for.SetPosition(yyDollar[1].tok.Position())
		}
	case 45:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:365
		{
			yyVAL.stmt_for = &ast.CForStmt{Stmt1: yyDollar[2].stmt_var_or_lets, Expr2: yyDollar[4].expr, Stmt: yyDollar[7].compstmt}
			yyVAL.stmt_for.SetPosition(yyDollar[1].tok.Position())
		}
	case 46:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser.go.y:370
		{
			yyVAL.stmt_for = &ast.CForStmt{Stmt1: yyDollar[2].stmt_var_or_lets, Expr2: yyDollar[4].expr, Expr3: yyDollar[6].expr, Stmt: yyDollar[8].compstmt}
			yyVAL.stmt_for.SetPosition(yyDollar[1].tok.Position())
		}
	case 47:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:377
		{
			yyVAL.stmt_select = &ast.SelectStmt{Body: yyDollar[4].stmt_select_cases}
			yyVAL.stmt_select.SetPosition(yyDollar[1].tok.Position())
		}
	case 48:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:384
		{
			yyVAL.stmt_select_cases = &ast.SelectBodyStmt{}
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:388
		{
			yyVAL.stmt_select_cases = &ast.SelectBodyStmt{Default: yyDollar[1].stmt_select_default}
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:392
		{
			yyVAL.stmt_select_cases = &ast.SelectBodyStmt{Cases: []ast.Stmt{yyDollar[1].stmt_select_case}}
		}
	case 51:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:396
		{
			selectStmt := yyDollar[1].stmt_select_cases.(*ast.SelectBodyStmt)
			selectStmt.Cases = append(selectStmt.Cases, yyDollar[2].stmt_select_case)
			yyVAL.stmt_select_cases = selectStmt
		}
	case 52:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:402
		{
			selectStmt := yyVAL.stmt_select_cases.(*ast.SelectBodyStmt)
			if selectStmt.Default != nil {
				yylex.Error("multiple default statement")
			}
			selectStmt.Default = yyDollar[2].stmt_select_default
			yyVAL.stmt_select_cases = selectStmt
		}
	case 53:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:413
		{
			if yyDollar[2].stmt == nil {
				yylex.Error("syntax error: unexpected ':'")
			}
			yyVAL.stmt_select_case = &ast.SelectCaseStmt{Expr: yyDollar[2].stmt, Stmt: yyDollar[4].compstmt}
			yyVAL.stmt_select_case.SetPosition(yyDollar[1].tok.Position())
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:423
		{
			yyVAL.stmt_select_default = yyDollar[3].compstmt
		}
	case 55:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:427
		{
			yyVAL.stmt_select_default = &ast.SelectCaseStmt{}
		}
	case 56:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:433
		{
			switchStmt := yyDollar[5].stmt_switch_cases.(*ast.SwitchStmt)
			switchStmt.Expr = yyDollar[2].expr
			yyVAL.stmt_switch = switchStmt
			yyVAL.stmt_switch.SetPosition(yyDollar[1].tok.Position())
		}
	case 57:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:442
		{
			yyVAL.stmt_switch_cases = &ast.SwitchStmt{}
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:446
		{
			yyVAL.stmt_switch_cases = &ast.SwitchStmt{Default: yyDollar[1].stmt_switch_default}
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:450
		{
			yyVAL.stmt_switch_cases = &ast.SwitchStmt{Cases: []ast.Stmt{yyDollar[1].stmt_switch_case}}
		}
	case 60:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:454
		{
			switchStmt := yyDollar[1].stmt_switch_cases.(*ast.SwitchStmt)
			switchStmt.Cases = append(switchStmt.Cases, yyDollar[2].stmt_switch_case)
			yyVAL.stmt_switch_cases = switchStmt
		}
	case 61:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:460
		{
			switchStmt := yyDollar[1].stmt_switch_cases.(*ast.SwitchStmt)
			if switchStmt.Default != nil {
				yylex.Error("multiple default statement")
			}
			switchStmt.Default = yyDollar[2].stmt_switch_default
		}
	case 62:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:470
		{
			yyVAL.stmt_switch_case = &ast.SwitchCaseStmt{Exprs: []ast.Expr{yyDollar[2].expr}, Stmt: yyDollar[4].compstmt}
			yyVAL.stmt_switch_case.SetPosition(yyDollar[1].tok.Position())
		}
	case 63:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:475
		{
			yyVAL.stmt_switch_case = &ast.SwitchCaseStmt{Exprs: yyDollar[2].exprs, Stmt: yyDollar[4].compstmt}
			yyVAL.stmt_switch_case.SetPosition(yyDollar[1].tok.Position())
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:482
		{
			yyVAL.stmt_switch_default = yyDollar[3].compstmt
		}
	case 65:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:489
		{
			yyVAL.exprs = nil
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:493
		{
			yyVAL.exprs = []ast.Expr{yyDollar[1].expr}
		}
	case 67:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:497
		{
			if len(yyDollar[1].exprs) == 0 {
				yylex.Error("syntax error: unexpected ','")
			}
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[4].expr)
		}
	case 68:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:504
		{
			if len(yyDollar[1].exprs) == 0 {
				yylex.Error("syntax error: unexpected ','")
			}
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[4].expr_ident)
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:513
		{
			yyVAL.expr = yyDollar[1].expr_member_or_ident
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:517
		{
			yyVAL.expr = yyDollar[1].expr_literals
		}
	case 71:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:521
		{
			yyVAL.expr = &ast.TernaryOpExpr{Expr: yyDollar[1].expr, LHS: yyDollar[3].expr, RHS: yyDollar[5].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:526
		{
			yyVAL.expr = &ast.NilCoalescingOpExpr{LHS: yyDollar[1].expr, RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 73:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:531
		{
			yyVAL.expr = &ast.FuncExpr{Params: yyDollar[3].expr_idents, Stmt: yyDollar[6].compstmt}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 74:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:536
		{
			yyVAL.expr = &ast.FuncExpr{Params: yyDollar[3].expr_idents, Stmt: yyDollar[7].compstmt, VarArg: true}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 75:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:541
		{
			yyVAL.expr = &ast.FuncExpr{Name: yyDollar[2].tok.Lit, Params: yyDollar[4].expr_idents, Stmt: yyDollar[7].compstmt}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 76:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser.go.y:546
		{
			yyVAL.expr = &ast.FuncExpr{Name: yyDollar[2].tok.Lit, Params: yyDollar[4].expr_idents, Stmt: yyDollar[8].compstmt, VarArg: true}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 77:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:551
		{
			yyVAL.expr = &ast.ArrayExpr{}
			if l, ok := yylex.(*Lexer); ok {
				yyVAL.expr.SetPosition(l.pos)
			}
		}
	case 78:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:556
		{
			yyVAL.expr = &ast.ArrayExpr{Exprs: yyDollar[3].exprs}
			if l, ok := yylex.(*Lexer); ok {
				yyVAL.expr.SetPosition(l.pos)
			}
		}
	case 79:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:561
		{
			yyVAL.expr = &ast.ArrayExpr{Exprs: yyDollar[5].exprs, TypeData: &ast.TypeStruct{Kind: ast.TypeSlice, SubType: yyDollar[2].type_data, Dimensions: yyDollar[1].slice_count}}
			if l, ok := yylex.(*Lexer); ok {
				yyVAL.expr.SetPosition(l.pos)
			}
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:566
		{
			yyVAL.expr = &ast.ParenExpr{SubExpr: yyDollar[2].expr}
			if l, ok := yylex.(*Lexer); ok {
				yyVAL.expr.SetPosition(l.pos)
			}
		}
	case 81:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:571
		{
			yyVAL.expr = &ast.CallExpr{Name: yyDollar[1].tok.Lit, SubExprs: yyDollar[3].exprs, VarArg: true}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 82:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:576
		{
			yyVAL.expr = &ast.CallExpr{Name: yyDollar[1].tok.Lit, SubExprs: yyDollar[3].exprs}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 83:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:581
		{
			yyVAL.expr = &ast.AnonCallExpr{Expr: yyDollar[1].expr, SubExprs: yyDollar[3].exprs, VarArg: true}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 84:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:586
		{
			yyVAL.expr = &ast.AnonCallExpr{Expr: yyDollar[1].expr, SubExprs: yyDollar[3].exprs}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 85:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:591
		{
			yyVAL.expr = &ast.ItemExpr{Item: yyDollar[1].expr_ident, Index: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr_ident.Position())
		}
	case 86:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:596
		{
			yyVAL.expr = &ast.ItemExpr{Item: yyDollar[1].expr, Index: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 87:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:601
		{
			yyVAL.expr = &ast.LenExpr{Expr: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 88:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:606
		{
			if yyDollar[3].type_data.Kind == ast.TypeDefault {
				yyDollar[3].type_data.Kind = ast.TypePtr
				yyVAL.expr = &ast.MakeExpr{TypeData: yyDollar[3].type_data}
			} else {
				yyVAL.expr = &ast.MakeExpr{TypeData: &ast.TypeStruct{Kind: ast.TypePtr, SubType: yyDollar[3].type_data}}
			}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 89:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:616
		{
			yyVAL.expr = &ast.MakeExpr{TypeData: yyDollar[3].type_data}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 90:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:621
		{
			yyVAL.expr = &ast.MakeExpr{TypeData: yyDollar[3].type_data, LenExpr: yyDollar[5].expr}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 91:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:626
		{
			yyVAL.expr = &ast.MakeExpr{TypeData: yyDollar[3].type_data, LenExpr: yyDollar[5].expr, CapExpr: yyDollar[7].expr}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 92:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:631
		{
			yyVAL.expr = &ast.MakeTypeExpr{Name: yyDollar[4].tok.Lit, Type: yyDollar[6].expr}
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 93:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:636
		{
			yyVAL.expr = &ast.ChanExpr{LHS: yyDollar[1].expr, RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 94:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:641
		{
			yyVAL.expr = &ast.ChanExpr{RHS: yyDollar[2].expr}
			yyVAL.expr.SetPosition(yyDollar[2].expr.Position())
		}
	case 95:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:646
		{
			yyVAL.expr = &ast.IncludeExpr{ItemExpr: yyDollar[1].expr, ListExpr: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 96:
		yyDollar = yyS[yypt-10 : yypt+1]
//line parser.go.y:651
		{
			yyDollar[8].expr_map.TypeData = &ast.TypeStruct{Kind: ast.TypeMap, Key: yyDollar[3].type_data, SubType: yyDollar[5].type_data}
			yyVAL.expr = yyDollar[8].expr_map
			yyVAL.expr.SetPosition(yyDollar[1].tok.Position())
		}
	case 97:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:657
		{
			yyVAL.expr = yyDollar[3].expr_map
			yyVAL.expr.SetPosition(yyDollar[3].expr_map.Position())
		}
	case 98:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:662
		{
			yyVAL.expr = yyDollar[1].expr_slice
			yyVAL.expr.SetPosition(yyDollar[1].expr_slice.Position())
		}
	case 102:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:671
		{
			yyVAL.expr_idents = []string{}
		}
	case 103:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:675
		{
			yyVAL.expr_idents = []string{yyDollar[1].tok.Lit}
		}
	case 104:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:679
		{
			if len(yyDollar[1].expr_idents) == 0 {
				yylex.Error("syntax error: unexpected ','")
			}
			yyVAL.expr_idents = append(yyDollar[1].expr_idents, yyDollar[4].tok.Lit)
		}
	case 105:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:688
		{
			yyVAL.type_data = &ast.TypeStruct{Name: yyDollar[1].tok.Lit}
		}
	case 106:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:692
		{
			if yyDollar[1].type_data.Kind != ast.TypeDefault {
				yylex.Error("blah1")
			} else {
				yyDollar[1].type_data.Env = append(yyDollar[1].type_data.Env, yyDollar[1].type_data.Name)
				yyDollar[1].type_data.Name = yyDollar[3].tok.Lit
			}
		}
	case 107:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:701
		{
			if yyDollar[2].type_data.Kind == ast.TypeDefault {
				yyDollar[2].type_data.Kind = ast.TypePtr
				yyVAL.type_data = yyDollar[2].type_data
			} else {
				yyVAL.type_data = &ast.TypeStruct{Kind: ast.TypePtr, SubType: yyDollar[2].type_data}
			}
		}
	case 108:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:710
		{
			if yyDollar[2].type_data.Kind == ast.TypeDefault {
				yyDollar[2].type_data.Kind = ast.TypeSlice
				yyDollar[2].type_data.Dimensions = yyDollar[1].slice_count
				yyVAL.type_data = yyDollar[2].type_data
			} else {
				yyVAL.type_data = &ast.TypeStruct{Kind: ast.TypeSlice, SubType: yyDollar[2].type_data, Dimensions: yyDollar[1].slice_count}
			}
		}
	case 109:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:720
		{
			yyVAL.type_data = &ast.TypeStruct{Kind: ast.TypeMap, Key: yyDollar[3].type_data, SubType: yyDollar[5].type_data}
		}
	case 110:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:724
		{
			if yyDollar[2].type_data.Kind == ast.TypeDefault {
				yyDollar[2].type_data.Kind = ast.TypeChan
				yyVAL.type_data = yyDollar[2].type_data
			} else {
				yyVAL.type_data = &ast.TypeStruct{Kind: ast.TypeChan, SubType: yyDollar[2].type_data}
			}
		}
	case 111:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:736
		{
			yyVAL.slice_count = 1
		}
	case 112:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:740
		{
			yyVAL.slice_count = yyDollar[3].slice_count + 1
		}
	case 113:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:746
		{
			yyVAL.expr_member_or_ident = yyDollar[1].expr_member
		}
	case 114:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:750
		{
			yyVAL.expr_member_or_ident = yyDollar[1].expr_ident
		}
	case 115:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:756
		{
			yyVAL.expr_member = &ast.MemberExpr{Expr: yyDollar[1].expr, Name: yyDollar[3].tok.Lit}
			yyVAL.expr_member.SetPosition(yyDollar[1].expr.Position())
		}
	case 116:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:763
		{
			yyVAL.expr_ident = &ast.IdentExpr{Lit: yyDollar[1].tok.Lit}
			yyVAL.expr_ident.SetPosition(yyDollar[1].tok.Position())
		}
	case 117:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:770
		{
			num, err := toNumber("-" + yyDollar[2].tok.Lit)
			if err != nil {
				yylex.Error("invalid number: -" + yyDollar[2].tok.Lit)
			}
			yyVAL.expr_literals = &ast.LiteralExpr{Literal: num}
			yyVAL.expr_literals.SetPosition(yyDollar[2].tok.Position())
		}
	case 118:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:779
		{
			num, err := toNumber(yyDollar[1].tok.Lit)
			if err != nil {
				yylex.Error("invalid number: " + yyDollar[1].tok.Lit)
			}
			yyVAL.expr_literals = &ast.LiteralExpr{Literal: num}
			yyVAL.expr_literals.SetPosition(yyDollar[1].tok.Position())
		}
	case 119:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:788
		{
			yyVAL.expr_literals = &ast.LiteralExpr{Literal: stringToValue(yyDollar[1].tok.Lit)}
			yyVAL.expr_literals.SetPosition(yyDollar[1].tok.Position())
		}
	case 120:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:793
		{
			yyVAL.expr_literals = &ast.LiteralExpr{Literal: trueValue}
			yyVAL.expr_literals.SetPosition(yyDollar[1].tok.Position())
		}
	case 121:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:798
		{
			yyVAL.expr_literals = &ast.LiteralExpr{Literal: falseValue}
			yyVAL.expr_literals.SetPosition(yyDollar[1].tok.Position())
		}
	case 122:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:803
		{
			yyVAL.expr_literals = &ast.LiteralExpr{Literal: nilValue}
			yyVAL.expr_literals.SetPosition(yyDollar[1].tok.Position())
		}
	case 123:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:810
		{
			yyVAL.expr_map = &ast.MapExpr{}
		}
	case 124:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:814
		{
			yyVAL.expr_map = &ast.MapExpr{Keys: []ast.Expr{yyDollar[1].expr}, Values: []ast.Expr{yyDollar[3].expr}}
		}
	case 125:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:818
		{
			if yyDollar[1].expr_map.Keys == nil {
				yylex.Error("syntax error: unexpected ','")
			}
			yyVAL.expr_map.Keys = append(yyVAL.expr_map.Keys, yyDollar[4].expr)
			yyVAL.expr_map.Values = append(yyVAL.expr_map.Values, yyDollar[6].expr)
		}
	case 126:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:828
		{
			yyVAL.expr_slice = &ast.SliceExpr{Item: yyDollar[1].expr_ident, Begin: yyDollar[3].expr, End: yyDollar[5].expr}
		}
	case 127:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:832
		{
			yyVAL.expr_slice = &ast.SliceExpr{Item: yyDollar[1].expr_ident, Begin: yyDollar[3].expr, End: nil}
		}
	case 128:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:836
		{
			yyVAL.expr_slice = &ast.SliceExpr{Item: yyDollar[1].expr_ident, Begin: nil, End: yyDollar[4].expr}
		}
	case 129:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:840
		{
			yyVAL.expr_slice = &ast.SliceExpr{Item: yyDollar[1].expr_ident, End: yyDollar[4].expr, Cap: yyDollar[6].expr}
		}
	case 130:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:844
		{
			yyVAL.expr_slice = &ast.SliceExpr{Item: yyDollar[1].expr_ident, Begin: yyDollar[3].expr, End: yyDollar[5].expr, Cap: yyDollar[7].expr}
		}
	case 131:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:848
		{
			yyVAL.expr_slice = &ast.SliceExpr{Item: yyDollar[1].expr, Begin: yyDollar[3].expr, End: yyDollar[5].expr}
		}
	case 132:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:852
		{
			yyVAL.expr_slice = &ast.SliceExpr{Item: yyDollar[1].expr, Begin: yyDollar[3].expr, End: nil}
		}
	case 133:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:856
		{
			yyVAL.expr_slice = &ast.SliceExpr{Item: yyDollar[1].expr, Begin: nil, End: yyDollar[4].expr}
		}
	case 134:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:860
		{
			yyVAL.expr_slice = &ast.SliceExpr{Item: yyDollar[1].expr, End: yyDollar[4].expr, Cap: yyDollar[6].expr}
		}
	case 135:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:864
		{
			yyVAL.expr_slice = &ast.SliceExpr{Item: yyDollar[1].expr, Begin: yyDollar[3].expr, End: yyDollar[5].expr, Cap: yyDollar[7].expr}
		}
	case 136:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:870
		{
			yyVAL.expr = &ast.UnaryExpr{Operator: "-", Expr: yyDollar[2].expr}
			yyVAL.expr.SetPosition(yyDollar[2].expr.Position())
		}
	case 137:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:875
		{
			yyVAL.expr = &ast.UnaryExpr{Operator: "!", Expr: yyDollar[2].expr}
			yyVAL.expr.SetPosition(yyDollar[2].expr.Position())
		}
	case 138:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:880
		{
			yyVAL.expr = &ast.UnaryExpr{Operator: "^", Expr: yyDollar[2].expr}
			yyVAL.expr.SetPosition(yyDollar[2].expr.Position())
		}
	case 139:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:885
		{
			yyVAL.expr = &ast.AddrExpr{Expr: yyDollar[2].expr}
			yyVAL.expr.SetPosition(yyDollar[2].expr.Position())
		}
	case 140:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:890
		{
			yyVAL.expr = &ast.DerefExpr{Expr: yyDollar[2].expr}
			yyVAL.expr.SetPosition(yyDollar[2].expr.Position())
		}
	case 141:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:897
		{
			yyVAL.expr = &ast.OpExpr{Op: yyDollar[1].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 142:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:902
		{
			yyVAL.expr = &ast.OpExpr{Op: yyDollar[1].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 143:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:907
		{
			yyVAL.expr = &ast.OpExpr{Op: yyDollar[1].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 144:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:912
		{
			yyVAL.expr = &ast.OpExpr{Op: yyDollar[1].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 145:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:919
		{
			rhs := &ast.OpExpr{Op: &ast.AddOperator{LHS: yyDollar[1].expr, Operator: "+", RHS: oneLiteral}}
			rhs.Op.SetPosition(yyDollar[1].expr.Position())
			rhs.SetPosition(yyDollar[1].expr.Position())
			yyVAL.expr = &ast.LetsExpr{LHSS: []ast.Expr{yyDollar[1].expr}, RHSS: []ast.Expr{rhs}}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 146:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:927
		{
			rhs := &ast.OpExpr{Op: &ast.AddOperator{LHS: yyDollar[1].expr, Operator: "-", RHS: oneLiteral}}
			rhs.Op.SetPosition(yyDollar[1].expr.Position())
			rhs.SetPosition(yyDollar[1].expr.Position())
			yyVAL.expr = &ast.LetsExpr{LHSS: []ast.Expr{yyDollar[1].expr}, RHSS: []ast.Expr{rhs}}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 147:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:935
		{
			rhs := &ast.OpExpr{Op: &ast.AddOperator{LHS: yyDollar[1].expr, Operator: "+", RHS: yyDollar[3].expr}}
			rhs.Op.SetPosition(yyDollar[1].expr.Position())
			rhs.SetPosition(yyDollar[1].expr.Position())
			yyVAL.expr = &ast.LetsExpr{LHSS: []ast.Expr{yyDollar[1].expr}, RHSS: []ast.Expr{rhs}}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 148:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:943
		{
			rhs := &ast.OpExpr{Op: &ast.AddOperator{LHS: yyDollar[1].expr, Operator: "-", RHS: yyDollar[3].expr}}
			rhs.Op.SetPosition(yyDollar[1].expr.Position())
			rhs.SetPosition(yyDollar[1].expr.Position())
			yyVAL.expr = &ast.LetsExpr{LHSS: []ast.Expr{yyDollar[1].expr}, RHSS: []ast.Expr{rhs}}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 149:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:951
		{
			rhs := &ast.OpExpr{Op: &ast.AddOperator{LHS: yyDollar[1].expr, Operator: "|", RHS: yyDollar[3].expr}}
			rhs.Op.SetPosition(yyDollar[1].expr.Position())
			rhs.SetPosition(yyDollar[1].expr.Position())
			yyVAL.expr = &ast.LetsExpr{LHSS: []ast.Expr{yyDollar[1].expr}, RHSS: []ast.Expr{rhs}}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 150:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:959
		{
			rhs := &ast.OpExpr{Op: &ast.MultiplyOperator{LHS: yyDollar[1].expr, Operator: "*", RHS: yyDollar[3].expr}}
			rhs.Op.SetPosition(yyDollar[1].expr.Position())
			rhs.SetPosition(yyDollar[1].expr.Position())
			yyVAL.expr = &ast.LetsExpr{LHSS: []ast.Expr{yyDollar[1].expr}, RHSS: []ast.Expr{rhs}}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 151:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:967
		{
			rhs := &ast.OpExpr{Op: &ast.MultiplyOperator{LHS: yyDollar[1].expr, Operator: "/", RHS: yyDollar[3].expr}}
			rhs.Op.SetPosition(yyDollar[1].expr.Position())
			rhs.SetPosition(yyDollar[1].expr.Position())
			yyVAL.expr = &ast.LetsExpr{LHSS: []ast.Expr{yyDollar[1].expr}, RHSS: []ast.Expr{rhs}}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 152:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:975
		{
			rhs := &ast.OpExpr{Op: &ast.MultiplyOperator{LHS: yyDollar[1].expr, Operator: "&", RHS: yyDollar[3].expr}}
			rhs.Op.SetPosition(yyDollar[1].expr.Position())
			rhs.SetPosition(yyDollar[1].expr.Position())
			yyVAL.expr = &ast.LetsExpr{LHSS: []ast.Expr{yyDollar[1].expr}, RHSS: []ast.Expr{rhs}}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 153:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:986
		{
			yyVAL.expr = &ast.MultiplyOperator{LHS: yyDollar[1].expr, Operator: "*", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 154:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:991
		{
			yyVAL.expr = &ast.MultiplyOperator{LHS: yyDollar[1].expr, Operator: "/", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 155:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:996
		{
			yyVAL.expr = &ast.MultiplyOperator{LHS: yyDollar[1].expr, Operator: "%", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 156:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1001
		{
			yyVAL.expr = &ast.MultiplyOperator{LHS: yyDollar[1].expr, Operator: "<<", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 157:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1006
		{
			yyVAL.expr = &ast.MultiplyOperator{LHS: yyDollar[1].expr, Operator: ">>", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 158:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1011
		{
			yyVAL.expr = &ast.MultiplyOperator{LHS: yyDollar[1].expr, Operator: "&", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 159:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1018
		{
			yyVAL.expr = &ast.AddOperator{LHS: yyDollar[1].expr, Operator: "+", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 160:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1023
		{
			yyVAL.expr = &ast.AddOperator{LHS: yyDollar[1].expr, Operator: "-", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 161:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1028
		{
			yyVAL.expr = &ast.AddOperator{LHS: yyDollar[1].expr, Operator: "|", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 162:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1035
		{
			yyVAL.expr = &ast.ComparisonOperator{LHS: yyDollar[1].expr, Operator: "==", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 163:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1040
		{
			yyVAL.expr = &ast.ComparisonOperator{LHS: yyDollar[1].expr, Operator: "!=", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 164:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1045
		{
			yyVAL.expr = &ast.ComparisonOperator{LHS: yyDollar[1].expr, Operator: "<", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 165:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1050
		{
			yyVAL.expr = &ast.ComparisonOperator{LHS: yyDollar[1].expr, Operator: "<=", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 166:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1055
		{
			yyVAL.expr = &ast.ComparisonOperator{LHS: yyDollar[1].expr, Operator: ">", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 167:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1060
		{
			yyVAL.expr = &ast.ComparisonOperator{LHS: yyDollar[1].expr, Operator: ">=", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 168:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1067
		{
			yyVAL.expr = &ast.BinaryOperator{LHS: yyDollar[1].expr, Operator: "&&", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	case 169:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:1072
		{
			yyVAL.expr = &ast.BinaryOperator{LHS: yyDollar[1].expr, Operator: "||", RHS: yyDollar[3].expr}
			yyVAL.expr.SetPosition(yyDollar[1].expr.Position())
		}
	}
	goto yystack /* stack new state and value */
}
